import React from 'react';
import { Check } from 'lucide-react';
import { PublicShell } from '../layout/PublicShell';
import { Card, cx } from '../ui';

const steps = ['Dịch vụ', 'Nhân viên', 'Thời gian', 'Thông tin', 'Xác nhận'];
export function BookingLayout({ step, title, description, children, aside }) {
  return <PublicShell><div className="mx-auto max-w-6xl"><nav aria-label="Tiến trình đặt lịch" className="mb-7 overflow-x-auto pb-2"><ol className="flex min-w-[640px] items-center">{steps.map((label, index) => { const number = index + 1; const done = number < step; const current = number === step; return <li key={label} className="flex flex-1 items-center last:flex-none"><span className="flex items-center gap-2"><span className={cx('grid h-8 w-8 place-items-center rounded-full border text-xs font-bold', done && 'border-[var(--bb-brand)] bg-[var(--bb-brand)] text-white', current && 'border-zinc-950 bg-zinc-950 text-white', !done && !current && 'border-[var(--bb-border)] bg-white text-[var(--bb-muted)]')}>{done ? <Check size={14} /> : number}</span><span className={cx('whitespace-nowrap text-xs font-semibold', current ? 'text-[var(--bb-ink)]' : 'text-[var(--bb-muted)]')}>{label}</span></span>{index < steps.length - 1 && <span className="mx-3 h-px flex-1 bg-[var(--bb-border)]" />}</li>; })}</ol></nav><header><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--bb-brand-strong)]">Bước {step} / 5</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--bb-muted)]">{description}</p></header><div className={cx('mt-7 grid gap-6', aside && 'lg:grid-cols-[minmax(0,1fr)_320px]')}><Card className="p-4 sm:p-6">{children}</Card>{aside && <aside>{aside}</aside>}</div></div></PublicShell>;
}

export function SelectionCard({ selected, title, meta, trailing, icon, onClick, disabled }) { return <button type="button" disabled={disabled} aria-pressed={selected} onClick={onClick} className={cx('flex min-h-20 w-full items-center gap-3 rounded-xl border p-4 text-left transition-colors disabled:opacity-50', selected ? 'border-[var(--bb-brand)] bg-[var(--bb-brand-soft)]' : 'border-[var(--bb-border)] bg-white hover:border-zinc-400 hover:bg-zinc-50')} >{icon && <span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-white text-[var(--bb-brand-strong)] shadow-sm">{icon}</span>}<span className="min-w-0 flex-1"><span className="block font-bold text-[var(--bb-ink)]">{title}</span>{meta && <span className="mt-1 block text-xs leading-5 text-[var(--bb-muted)]">{meta}</span>}</span>{trailing && <span className="shrink-0 text-sm font-bold text-[var(--bb-brand-strong)]">{trailing}</span>}</button>; }

export function WizardActions({ back, next, nextLabel = 'Tiếp tục', nextDisabled, loading }) { return <div className="mt-6 flex flex-col-reverse gap-2 border-t border-[var(--bb-border)] pt-5 sm:flex-row sm:justify-between">{back}<span className="sm:ml-auto">{React.isValidElement(next) ? next : null}</span></div>; }
