import React, { useEffect, useState } from 'react';
import { addDays, format } from 'date-fns';
import toast from 'react-hot-toast';
import { bookingsApi } from '../../api/apiClient';
import { Button, Dialog, EmptyState, ErrorState, Field, InlineNotice, Skeleton, Textarea, cx } from '../ui';

export function RescheduleModal({ booking, onClose, onSuccess }) {
  const [date, setDate] = useState(booking.appointmentStartTime?.slice(0,10) || ''); const [slots, setSlots] = useState([]); const [slot, setSlot] = useState(null); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const serviceIds = (booking.bookingServices || []).map((item) => item.serviceId);
  const load = async () => { if (!date || !serviceIds.length) return; setLoading(true); setError(''); try { const result = await bookingsApi.availableSlots({ branchId: booking.branchId, staffId: booking.bookingServices?.[0]?.staffId || '', serviceIds, date }); setSlots(result.slots || []); setSlot(null); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [date, booking.branchId]);
  const submit = async () => { if (!slot || !reason.trim()) return; setSubmitting(true); try { await bookingsApi.createChangeRequest(booking.id, { requestType: 'RESCHEDULE', proposedStartTime: slot.start, proposedEndTime: slot.end, proposedStaffId: booking.bookingServices?.[0]?.staffId || undefined, reason: reason.trim() }); toast.success('Đã gửi yêu cầu đổi lịch'); onSuccess(); } catch (e) { toast.error(e.message || 'Gửi yêu cầu thất bại'); } finally { setSubmitting(false); } };
  const days = Array.from({ length: 7 }, (_, i) => addDays(new Date(), i));
  return <Dialog open onClose={onClose} title="Yêu cầu đổi lịch" description={`Lịch hiện tại: ${format(new Date(booking.appointmentStartTime), 'dd/MM/yyyy · HH:mm')}. Lịch cũ vẫn được giữ cho đến khi cơ sở duyệt.`} footer={<><Button variant="secondary" onClick={onClose}>Hủy</Button><Button loading={submitting} disabled={!slot || !reason.trim()} onClick={submit}>Gửi yêu cầu</Button></>}><h3 className="text-sm font-bold">Chọn ngày mới</h3><div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-7">{days.map((day) => { const iso = format(day, 'yyyy-MM-dd'); return <button key={iso} type="button" aria-pressed={date === iso} onClick={() => setDate(iso)} className={cx('min-h-16 rounded-lg border text-xs', date === iso ? 'border-zinc-950 bg-zinc-950 text-white' : 'border-[var(--bb-border)]')}><b className="block text-base">{format(day, 'd')}</b>tháng {format(day, 'M')}</button>; })}</div><h3 className="mt-5 text-sm font-bold">Khung giờ trống</h3><div className="mt-3">{loading ? <Skeleton rows={3} /> : error ? <ErrorState message={error} onRetry={load} /> : !slots.length ? <EmptyState title="Không có giờ trống" description="Hãy chọn ngày khác." /> : <div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map((item) => <button key={item.start} type="button" aria-pressed={slot?.start === item.start} onClick={() => setSlot(item)} className={cx('min-h-11 rounded-lg border text-sm font-bold', slot?.start === item.start ? 'border-[var(--bb-brand)] bg-[var(--bb-brand-soft)] text-[var(--bb-brand-strong)]' : 'border-[var(--bb-border)]')}>{format(new Date(item.start), 'HH:mm')}</button>)}</div>}</div><Field label="Lý do đổi lịch" required className="mt-5"><Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Cho cơ sở biết lý do bạn cần đổi lịch" /></Field><div className="mt-4"><InlineNotice tone="warning">Đây là yêu cầu đổi lịch, không cập nhật trực tiếp booking. Cơ sở sẽ duyệt hoặc từ chối theo workflow hiện tại.</InlineNotice></div></Dialog>;
}
