ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'NEED_MORE_INFO';
ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'APPROVED';

ALTER TABLE "businesses"
  ADD COLUMN IF NOT EXISTS "contact_email" TEXT,
  ADD COLUMN IF NOT EXISTS "contact_phone" TEXT,
  ADD COLUMN IF NOT EXISTS "address_line" TEXT,
  ADD COLUMN IF NOT EXISTS "legal_representative" TEXT,
  ADD COLUMN IF NOT EXISTS "legal_documents" JSONB,
  ADD COLUMN IF NOT EXISTS "review_note" TEXT,
  ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "reviewed_at" TIMESTAMP(3);
