const {test}=require('node:test'), assert=require('node:assert/strict'), ts=require('typescript'), fs=require('node:fs'), vm=require('node:vm');
const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/utils/actualTimeCorrection.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module:m,exports:m.exports,Date,Intl,Number,Error,Set,Object});
const {branchActualInstant,correctionPayload}=m.exports;
const known={startDay:'2026-10-06',startTime:'22:00',endDay:'2026-10-06',endTime:'22:30',timezone:'Asia/Ho_Chi_Minh',unknown:false,reason:'Nhân viên quên cập nhật trạng thái dịch vụ',expectedRevision:3,serverNow:Date.parse('2026-10-06T15:52:00Z')};
test('22:00–22:30 corrected times use branch timezone and explicit operator facts',()=>{const p=correctionPayload(known);assert.equal(p.actualStartedAt,'2026-10-06T15:00:00.000Z');assert.equal(p.actualCompletedAt,'2026-10-06T15:30:00.000Z');assert.equal(p.expectedRevision,3);assert.equal(p.reason,known.reason);assert.ok(!('itemStartAt' in p));});
test('blank inputs never take planned time; reason required even for UNKNOWN',()=>{assert.throws(()=>correctionPayload({...known,startDay:'',startTime:'',endDay:'',endTime:''}),/chính xác/);assert.throws(()=>correctionPayload({...known,unknown:true,reason:''}),/lý do/);});
test('UNKNOWN explicitly keeps both actual fields null',()=>{const p=correctionPayload({...known,unknown:true});assert.equal(p.actualStartedAt,null);assert.equal(p.actualCompletedAt,null);});
test('invalid/reversed/equal/future actuals and missing server clock reject',()=>{for(const change of [{endTime:'22:00'},{endTime:'21:00'},{endTime:'23:00'},{serverNow:NaN},{expectedRevision:0},{startDay:'2026-02-30'}])assert.throws(()=>correctionPayload({...known,...change}));});
test('DST ambiguous/nonexistent local time and invalid timezone never guessed',()=>{assert.equal(branchActualInstant('2026-11-01','01:30','America/New_York'),null);assert.equal(branchActualInstant('2026-03-08','02:30','America/New_York'),null);assert.equal(branchActualInstant('2026-10-06','22:00','invalid'),null);});
