import React, { useState } from 'react';
import { ArrowRightLeft, Calendar, UserRound } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import toast from 'react-hot-toast';
import { bookingsApi } from '../../api/apiClient';
import { normalizeBooking } from '../../utils/bookingCalendar.adapter';
import { Badge, Button, Card, Dialog, Field, Textarea } from '../ui';

const labels = { RESCHEDULE:'Đổi giờ', STAFF_CHANGE:'Đổi nhân viên', CANCEL:'Hủy lịch' };
export function ChangeRequestCard({ request, onUpdated }) { const [busy, setBusy] = useState(''); const [rejectOpen, setRejectOpen] = useState(false); const [note, setNote] = useState(''); const current = request.booking ? normalizeBooking(request.booking).startAt : null; const proposed = request.proposedStartTime ? parseISO(request.proposedStartTime) : null; const approve = async () => { setBusy('approve'); try { await bookingsApi.approveChangeRequest(request.id); toast.success('Đã duyệt yêu cầu'); onUpdated?.(); } catch (e) { toast.error(e.message); } finally { setBusy(''); } }; const reject = async () => { if (note.trim().length < 3) return; setBusy('reject'); try { await bookingsApi.rejectChangeRequest(request.id, note.trim()); toast.success('Đã từ chối yêu cầu'); setRejectOpen(false); onUpdated?.(); } catch (e) { toast.error(e.message); } finally { setBusy(''); } }; return <><Card as="article" className="overflow-hidden"><header className="flex items-start gap-3 border-b border-[var(--bb-border)] p-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-pink-50 text-pink-700"><ArrowRightLeft size={18} /></span><div className="min-w-0 flex-1"><h3 className="font-bold">{labels[request.requestType] || request.requestType}</h3><p className="mt-1 text-xs text-[var(--bb-muted)]">{request.requestedByUser?.fullName || 'Khách hàng'} · <span className="bb-mono">{request.booking?.bookingCode || '—'}</span></p></div><Badge tone="warning">PENDING</Badge></header><div className="grid gap-3 p-5 sm:grid-cols-2"><Compare label="Hiện tại" date={current} staff={request.booking?.bookingServices?.[0]?.staff} /><Compare label="Đề xuất" date={proposed} staff={request.proposedStaff} highlight /></div>{request.reason && <blockquote className="mx-5 mb-5 rounded-lg bg-[var(--bb-surface-subtle)] p-3 text-sm text-[var(--bb-ink-soft)]">“{request.reason}”</blockquote>}<footer className="flex flex-wrap justify-end gap-2 border-t border-[var(--bb-border)] p-4"><Button variant="secondary" disabled={Boolean(busy)} onClick={() => setRejectOpen(true)}>Từ chối</Button><Button loading={busy === 'approve'} onClick={approve}>Duyệt yêu cầu</Button></footer></Card><Dialog open={rejectOpen} onClose={() => setRejectOpen(false)} title="Từ chối yêu cầu thay đổi" description="Lý do sẽ được gửi cho khách hàng; booking hiện tại không bị thay đổi." footer={<><Button variant="secondary" onClick={() => setRejectOpen(false)}>Hủy</Button><Button variant="danger" loading={busy === 'reject'} disabled={note.trim().length < 3} onClick={reject}>Xác nhận từ chối</Button></>}><Field label="Lý do từ chối" required><Textarea value={note} onChange={(e) => setNote(e.target.value)} /></Field></Dialog></>; }
function Compare({ label, date, staff, highlight }) { return <div className={highlight ? 'rounded-xl border border-pink-200 bg-pink-50 p-4' : 'rounded-xl border border-[var(--bb-border)] p-4'}><p className="text-xs font-bold uppercase tracking-wide text-[var(--bb-muted)]">{label}</p><p className="mt-2 flex items-center gap-2 text-sm font-bold"><Calendar size={15} />{date ? format(date, 'HH:mm · dd/MM/yyyy') : '—'}</p>{staff && <p className="mt-2 flex items-center gap-2 text-xs text-[var(--bb-muted)]"><UserRound size={14} />{staff.user?.fullName || staff.fullName || '—'}</p>}</div>; }
export default ChangeRequestCard;
