import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { LayoutGrid, List, Pencil, Plus, Scissors, Search, ShieldX, UserCog, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { branchesApi, servicesApi, staffApi } from '../../api/apiClient';
import { useAuthStore } from '../../store/authStore';
import { FileUpload } from '../../components/media/FileUpload';
import { Badge, Button, Card, Dialog, EmptyState, ErrorState, Field, InlineNotice, Input, MetricCard, Page, PageHeader, Select, Skeleton, Textarea } from '../../components/ui';

const statusMeta = {
  PROFILE_ONLY: ['Chỉ có hồ sơ', 'neutral'],
  INVITED: ['Đã gửi lời mời', 'info'],
  ACTIVE: ['Hoạt động', 'success'],
  LOCKED: ['Đã khóa', 'danger'],
  INACTIVE: ['Đã ngừng làm việc', 'danger'],
};
function StaffCard({ staff, capabilities, onView, onEdit, onServices, onDeactivate }) {
  const [label, tone] = statusMeta[staff.status] || [staff.status || '—', 'neutral'];
  return <Card className="min-w-0 flex min-h-72 flex-col p-5">
    <div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-pink-50 text-lg font-bold text-pink-700" aria-hidden="true">{staff.fullName?.slice(0, 1).toUpperCase() || '?'}</span><div className="min-w-0 flex-1"><h2 className="truncate font-bold text-[var(--bb-ink)]">{staff.fullName}</h2><p className="mt-0.5 text-sm text-[var(--bb-muted)]">{staff.position || 'Nhân viên'}</p><p className="mt-0.5 truncate text-xs text-[var(--bb-muted)]">{staff.branch?.name || '—'}</p></div><Badge tone={tone}>{label}</Badge></div>
    <div className="mt-3 flex flex-wrap gap-2"><Badge tone={staff.isBookable ? 'success' : 'neutral'}>{staff.isBookable ? 'Nhận lịch' : 'Không nhận lịch'}</Badge>{staff.publicVisible ? <Badge tone="info">Hồ sơ công khai</Badge> : null}</div>
    <p className="mt-4 break-all text-xs text-[var(--bb-muted)]">{staff.services?.length || 0} dịch vụ{staff.user?.email ? ` · ${staff.user.email}` : ''}</p>
    <div className="mt-auto flex flex-wrap gap-2 border-t border-[var(--bb-border)] pt-4">{capabilities.readDetail && <Button size="sm" onClick={() => onView(staff)}><UserCog size={14} />Chi tiết</Button>}{capabilities.manageStaff && <Button size="sm" variant="secondary" onClick={() => onEdit(staff)}><Pencil size={14} />Hồ sơ</Button>}{capabilities.manageServices && <Button size="sm" variant="secondary" onClick={() => onServices(staff)}><Scissors size={14} />Dịch vụ</Button>}{capabilities.manageStaff && staff.status === 'ACTIVE' && <Button size="sm" variant="ghost" className="text-[var(--bb-danger)]" onClick={() => onDeactivate(staff)}><ShieldX size={14} />Khóa</Button>}</div>
  </Card>;
}

function StaffTable({ staff, capabilities, onView, onEdit, onServices, onDeactivate }) {
  return <Card className="overflow-x-auto"><table className="min-w-[860px] w-full text-left text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-xs uppercase tracking-wide text-[var(--bb-muted)]"><tr><th className="px-4 py-3">Nhân viên</th><th className="px-4 py-3">Chi nhánh</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Dịch vụ</th><th className="px-4 py-3">Hành động</th></tr></thead><tbody className="divide-y divide-[var(--bb-border)]">{staff.map((item) => { const [label, tone] = statusMeta[item.status] || [item.status || '—', 'neutral']; return <tr key={item.id} className="align-top"><td className="px-4 py-4"><p className="font-bold">{item.fullName}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{item.position || 'Nhân viên'}{item.user?.email ? ` · ${item.user.email}` : ''}</p></td><td className="px-4 py-4">{item.branch?.name || '—'}</td><td className="px-4 py-4"><Badge tone={tone}>{label}</Badge></td><td className="px-4 py-4">{item.services?.length || 0}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{capabilities.readDetail && <Button size="sm" onClick={() => onView(item)}><UserCog size={14} />Chi tiết</Button>}{capabilities.manageStaff && <Button size="sm" variant="secondary" onClick={() => onEdit(item)}><Pencil size={14} />Hồ sơ</Button>}{capabilities.manageServices && <Button size="sm" variant="secondary" onClick={() => onServices(item)}><Scissors size={14} />Dịch vụ</Button>}{capabilities.manageStaff && item.status === 'ACTIVE' && <Button size="sm" variant="ghost" className="text-[var(--bb-danger)]" onClick={() => onDeactivate(item)}><ShieldX size={14} />Khóa</Button>}</div></td></tr>; })}</tbody></table></Card>;
}

function StaffForm({ modal, branches, onClose, onSaved }) {
  const editing = Boolean(modal?.id);
  const [form, setForm] = useState({ branchId: '', fullName: '', position: '', bio: '', status: 'PROFILE_ONLY', isBookable: false, publicVisible: false, accountMode: 'LATER', email: '', roleCode: 'STAFF' });
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState({});
  const [portfolio, setPortfolio] = useState(null);
  useEffect(() => { if (modal === null) return; setForm({ branchId: modal?.branchId || branches[0]?.id || '', fullName: modal?.fullName || '', position: modal?.position || '', bio: modal?.bio || '', status: modal?.status || 'PROFILE_ONLY', isBookable: modal?.isBookable ?? false, publicVisible: modal?.publicVisible ?? false, accountMode: 'LATER', email: '', roleCode: 'STAFF' }); setPortfolio(modal?.images?.[0]?.media || null); setErrors({}); }, [modal, branches]);
  const set = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); const next = {}; if (!form.fullName.trim()) next.fullName = 'Nhập họ tên.'; if (!editing && !form.branchId) next.branchId = 'Chọn chi nhánh.'; if (!editing && form.accountMode === 'INVITE' && !form.email.trim()) next.email = 'Nhập email nhận lời mời.'; setErrors(next); if (Object.keys(next).length) return; setSaving(true); try { const payload = { fullName: form.fullName.trim(), position: form.position.trim(), bio: form.bio.trim(), isBookable: form.isBookable, publicVisible: form.publicVisible, ...(editing ? { status: form.status } : { branchId: form.branchId }) }; if (editing) { await staffApi.update(modal.id, payload); } else { const profile = await staffApi.create(payload); if (form.accountMode === 'INVITE') { const selectedBranch = branches.find((item) => item.id === form.branchId); await staffApi.invite({ staffProfileId: profile.id, email: form.email.trim(), roleCode: form.roleCode, businessId: selectedBranch.businessId, branchId: form.branchId }); } } toast.success(editing ? 'Đã cập nhật nhân viên' : form.accountMode === 'INVITE' ? 'Đã tạo hồ sơ và gửi lời mời' : 'Đã lưu hồ sơ nhân sự'); onSaved(); } catch (error) { toast.error(error.message || 'Không thể lưu nhân viên'); } finally { setSaving(false); } };
  return <Dialog open={modal !== null} onClose={onClose} title={editing ? 'Sửa hồ sơ nhân viên' : 'Thêm nhân sự'} description={editing ? 'Cập nhật hồ sơ nhân sự trong phạm vi chi nhánh được cấp.' : 'Một luồng duy nhất: tạo hồ sơ, chọn vai trò rồi cấp tài khoản ngay hoặc để sau.'} footer={<><Button variant="secondary" onClick={onClose}>Hủy</Button><Button type="submit" form="staff-form" loading={saving}>Lưu</Button></>}>
    <form id="staff-form" onSubmit={submit} className="grid gap-4">
      {editing && <FileUpload entityType="STAFF_IMAGE" entityId={modal.id} businessId={modal.branch?.businessId} branchId={modal.branch?.id} value={portfolio} label="Ảnh chuyên môn / portfolio" onUploaded={setPortfolio} onRemoved={() => setPortfolio(null)} />}
      {!editing && <Field label="Chi nhánh" required error={errors.branchId}><Select value={form.branchId} onChange={set('branchId')}><option value="">Chọn chi nhánh</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></Field>}
      <Field label="Họ tên" required error={errors.fullName}><Input autoFocus value={form.fullName} onChange={set('fullName')} /></Field>
      <Field label="Vị trí"><Input value={form.position} onChange={set('position')} placeholder="Chuyên viên spa" /></Field>
      <Field label="Giới thiệu"><Textarea value={form.bio} onChange={set('bio')} /></Field>
      {!editing && <div className="grid gap-4 rounded-xl border border-[var(--bb-border)] p-4"><Field label="Cấp tài khoản"><Select value={form.accountMode} onChange={set('accountMode')}><option value="LATER">Để sau — chỉ tạo hồ sơ</option><option value="INVITE">Gửi lời mời qua email ngay</option></Select></Field>{form.accountMode === 'INVITE' && <><Field label="Email nhận lời mời" required error={errors.email}><Input type="email" autoComplete="email" value={form.email} onChange={set('email')} /></Field><Field label="Vai trò làm việc" required><Select value={form.roleCode} onChange={set('roleCode')}><option value="STAFF">Nhân viên dịch vụ</option><option value="RECEPTIONIST">Lễ tân</option></Select></Field></>}</div>}
      <div className="grid gap-3 rounded-xl border border-[var(--bb-border)] p-4 sm:grid-cols-2">
        <label className="flex cursor-pointer items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={form.isBookable} onChange={(event) => setForm((value) => ({ ...value, isBookable: event.target.checked }))} /><span><strong className="block">Cho phép nhận lịch</strong><small className="mt-1 block leading-5 text-[var(--bb-muted)]">Chỉ bật khi người này trực tiếp thực hiện dịch vụ.</small></span></label>
        <label className="flex cursor-pointer items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={form.publicVisible} disabled={!form.isBookable} onChange={(event) => setForm((value) => ({ ...value, publicVisible: event.target.checked }))} /><span><strong className="block">Hiện trên trang công khai</strong><small className="mt-1 block leading-5 text-[var(--bb-muted)]">Hồ sơ chỉ xuất hiện khi đã bật nhận lịch và có dịch vụ phù hợp.</small></span></label>
      </div>
      {editing && <Field label="Trạng thái"><Select value={form.status} onChange={set('status')}><option value="PROFILE_ONLY">Chỉ có hồ sơ</option><option value="INVITED">Đã gửi lời mời</option><option value="ACTIVE">Hoạt động</option><option value="LOCKED">Đã khóa</option><option value="INACTIVE">Đã ngừng làm việc</option></Select></Field>}
      <p className="text-xs leading-5 text-[var(--bb-muted)]">{modal?.userId || modal?.user ? 'Hồ sơ đã liên kết tài khoản đăng nhập.' : 'Chưa có tài khoản đăng nhập; việc tạo hồ sơ không tự cấp mật khẩu hoặc vai trò.'}</p>
    </form>
  </Dialog>;
}

function InviteForm({ open, branches, onClose, onSent }) {
  const [form, setForm] = useState({ email: '', roleCode: 'STAFF', branchId: '' });
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) setForm({ email: '', roleCode: 'STAFF', branchId: branches[0]?.id || '' }); }, [open, branches]);
  const submit = async (event) => { event.preventDefault(); const branch = branches.find((item) => item.id === form.branchId); if (!branch?.businessId) return toast.error('Chi nhánh chưa có businessId hợp lệ'); setSaving(true); try { await staffApi.invite({ ...form, email: form.email.trim(), businessId: branch.businessId }); toast.success('Đã gửi lời mời nhân viên'); onSent(); } catch (error) { toast.error(error.message || 'Không thể gửi lời mời'); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title="Mời nhân viên" description="Người nhận dùng email này để chấp nhận lời mời và vào đúng doanh nghiệp/chi nhánh." footer={<><Button variant="secondary" onClick={onClose}>Hủy</Button><Button type="submit" form="invite-staff" loading={saving}>Gửi lời mời</Button></>}><form id="invite-staff" onSubmit={submit} className="grid gap-4"><Field label="Email" required><Input type="email" autoComplete="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></Field><Field label="Vai trò" required><Select value={form.roleCode} onChange={(event) => setForm({ ...form, roleCode: event.target.value })}><option value="STAFF">Nhân viên</option><option value="RECEPTIONIST">Lễ tân</option></Select></Field><Field label="Chi nhánh" required><Select required value={form.branchId} onChange={(event) => setForm({ ...form, branchId: event.target.value })}><option value="">Chọn chi nhánh</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></Field></form></Dialog>;
}

function ServiceAssignment({ staff, onClose, onSaved }) {
  const [services, setServices] = useState([]); const [selected, setSelected] = useState(new Set()); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!staff) return; setSelected(new Set(staff.services?.map((item) => item.id) || [])); setLoading(true); servicesApi.getManage().then((data) => setServices(Array.isArray(data) ? data : data?.data || [])).catch((error) => toast.error(error.message || 'Không thể tải dịch vụ')).finally(() => setLoading(false)); }, [staff]);
  const toggle = (id) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const save = async () => { setSaving(true); try { await staffApi.assignServices(staff.id, [...selected]); toast.success('Đã cập nhật dịch vụ phụ trách'); onSaved(); } catch (error) { toast.error(error.message || 'Không thể gán dịch vụ'); } finally { setSaving(false); } };
  return <Dialog open={Boolean(staff)} onClose={onClose} title="Dịch vụ phụ trách" description={staff?.fullName} footer={<><Button variant="secondary" onClick={onClose}>Đóng</Button><Button loading={saving} onClick={save}>Lưu ({selected.size})</Button></>}>{loading ? <Skeleton rows={5} /> : services.length === 0 ? <EmptyState title="Chưa có dịch vụ" /> : <div className="space-y-2">{services.map((service) => <label key={service.id} className="flex cursor-pointer items-center gap-3 rounded-lg border border-[var(--bb-border)] p-3"><input type="checkbox" checked={selected.has(service.id)} onChange={() => toggle(service.id)} /><span className="min-w-0 flex-1"><strong className="block text-sm">{service.name}</strong><span className="text-xs text-[var(--bb-muted)]">{Number(service.price || 0).toLocaleString('vi-VN')} ₫ · {service.durationMinutes || service.duration || 0} phút</span></span></label>)}</div>}</Dialog>;
}

export function SalonStaffManagement() {
  const navigate = useNavigate();
  const can = useAuthStore((state) => state.can);
  const capabilities = { manageStaff: can('user:role_assign:tenant'), readDetail: can('user:read:tenant') || can('user:read:branch') || can('user:read:platform'), manageServices: can('staff_service:assign:tenant') };
  const [staff, setStaff] = useState([]); const [branches, setBranches] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL'); const [branch, setBranch] = useState('ALL'); const [view, setView] = useState('grid'); const [editor, setEditor] = useState(null); const [services, setServices] = useState(null); const [deactivate, setDeactivate] = useState(null); const [offboardingReason, setOffboardingReason] = useState(''); const [offboardingImpact, setOffboardingImpact] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const [staffData, branchData] = await Promise.all([staffApi.getAll(), branchesApi.getAccessible()]); setStaff(Array.isArray(staffData) ? staffData : staffData?.data || []); setBranches(Array.isArray(branchData) ? branchData : branchData?.data || []); } catch (loadError) { setError(loadError.message || 'Không thể tải dữ liệu nhân sự.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => staff.filter((item) => { const query = search.trim().toLocaleLowerCase('vi'); return (!query || item.fullName?.toLocaleLowerCase('vi').includes(query) || item.position?.toLocaleLowerCase('vi').includes(query)) && (status === 'ALL' || item.status === status) && (branch === 'ALL' || item.branchId === branch || item.branch?.id === branch); }), [staff, search, status, branch]);
  const openDeactivate = async (selected) => { setDeactivate(selected); setOffboardingReason(''); setOffboardingImpact(null); try { setOffboardingImpact(await staffApi.getOffboardingImpact(selected.id)); } catch (error) { toast.error(error.message || 'Không thể tải ảnh hưởng offboarding'); } };
  const deactivateStaff = async () => { if (!deactivate) return; if (!offboardingReason.trim()) return toast.error('Nhập lý do ngừng làm việc'); setBusy(true); try { const result = await staffApi.deactivate(deactivate.id, { reason: offboardingReason.trim() }); setDeactivate(null); if (result?.requiresImpactResolution) { toast.success('Đã tạo hồ sơ xử lý các lịch bị ảnh hưởng'); navigate(`/salon/operations?impactCase=${result.impactCase?.id || ''}`); return; } toast.success('Đã ngừng quyền làm việc; tài khoản khách hàng vẫn được giữ'); await load(); } catch (error) { toast.error(error.message || 'Không thể ngừng nhân sự'); } finally { setBusy(false); } };
  const closeAndReload = (setter) => async () => { setter(null); await load(); };
  return <Page>
    <PageHeader eyebrow="Vận hành chi nhánh" title="Nhân sự" description="Quản lý hồ sơ, quyền truy cập, chi nhánh và dịch vụ mà từng chuyên viên có thể thực hiện." actions={capabilities.manageStaff && <Button onClick={() => setEditor({})}><Plus size={17} />Thêm nhân sự</Button>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Users} label="Tổng nhân viên" value={staff.length} /><MetricCard icon={UserCog} label="Đang hoạt động" value={staff.filter((item) => item.status === 'ACTIVE').length} tone="success" /><MetricCard icon={Scissors} label="Đang nhận lịch" value={staff.filter((item) => item.status === 'ACTIVE' && item.isBookable).length} tone="info" /><MetricCard icon={ShieldX} label="Tạm ngưng nhận lịch" value={staff.filter((item) => item.status === 'INACTIVE').length} tone="neutral" /></div>
    <Card className="p-4"><div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_190px_220px_auto]"><Field label="Tìm nhân viên"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-[var(--bb-muted)]" size={16} /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tên hoặc vị trí" /></div></Field><Field label="Trạng thái"><Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">Tất cả</option><option value="PROFILE_ONLY">Chỉ có hồ sơ</option><option value="INVITED">Đã gửi lời mời</option><option value="ACTIVE">Hoạt động</option><option value="LOCKED">Đã khóa</option><option value="INACTIVE">Đã ngừng làm việc</option></Select></Field><Field label="Chi nhánh"><Select value={branch} onChange={(event) => setBranch(event.target.value)}><option value="ALL">Tất cả chi nhánh</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><div className="flex items-end"><div className="flex rounded-xl border border-[var(--bb-border)] p-1"><Button size="icon" variant={view === 'grid' ? 'primary' : 'ghost'} aria-label="Xem dạng thẻ" onClick={() => setView('grid')}><LayoutGrid size={17} /></Button><Button size="icon" variant={view === 'table' ? 'primary' : 'ghost'} aria-label="Xem dạng bảng" onClick={() => setView('table')}><List size={17} /></Button></div></div></div></Card>
    {loading ? <Card className="p-5"><Skeleton rows={7} /></Card> : error ? <Card><ErrorState message={error} onRetry={load} /></Card> : filtered.length === 0 ? <Card><EmptyState icon={Users} title="Không có nhân viên phù hợp" description={staff.length ? 'Thử đổi bộ lọc.' : 'Chưa có nhân viên trong phạm vi được cấp.'} action={capabilities.manageStaff && !staff.length ? <Button onClick={() => setEditor({})}>Thêm nhân viên</Button> : null} /></Card> : view === 'grid' ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <StaffCard key={item.id} staff={item} capabilities={capabilities} onView={(selected) => navigate(`/salon/staff/${selected.id}`)} onEdit={setEditor} onServices={setServices} onDeactivate={openDeactivate} />)}</div> : <StaffTable staff={filtered} capabilities={capabilities} onView={(selected) => navigate(`/salon/staff/${selected.id}`)} onEdit={setEditor} onServices={setServices} onDeactivate={openDeactivate} />}
    <StaffForm modal={editor} branches={branches} onClose={() => setEditor(null)} onSaved={closeAndReload(setEditor)} /><ServiceAssignment staff={services} onClose={() => setServices(null)} onSaved={closeAndReload(setServices)} />
    <Dialog open={Boolean(deactivate)} onClose={() => setDeactivate(null)} title="Ngừng quyền làm việc?" description={deactivate?.fullName} footer={<><Button variant="secondary" onClick={() => setDeactivate(null)}>Hủy</Button><Button variant="danger" loading={busy} onClick={deactivateStaff}>{offboardingImpact?.futureBookingCount > 0 ? 'Tạo hồ sơ xử lý' : 'Xác nhận ngừng làm việc'}</Button></>}><div className="space-y-4"><InlineNotice tone="warning">Hồ sơ và lịch sử được giữ nguyên. Chỉ role/membership và phiên SALON của doanh nghiệp này bị thu hồi; quyền Customer không bị ảnh hưởng.</InlineNotice><Field label="Lý do" required><Textarea value={offboardingReason} onChange={(event) => setOffboardingReason(event.target.value)} /></Field>{offboardingImpact?.futureBookingCount > 0 && <InlineNotice tone="warning"><strong>{offboardingImpact.futureBookingCount} lịch tương lai phải được xử lý</strong><p className="mt-1">Hệ thống sẽ tạo hồ sơ tại Trung tâm vận hành. Nhân viên chỉ được ngừng sau khi từng lịch đã reassign, reschedule, chuyển chi nhánh, hủy/hoàn tiền hoặc được duyệt ngoại lệ.</p></InlineNotice>}</div></Dialog>
  </Page>;
}

export default SalonStaffManagement;
