import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CalendarDays, Clock3, LayoutGrid, List, Pencil, Plus, Scissors, Search, ShieldX, UserCog, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { branchesApi, servicesApi, staffApi } from '../../api/apiClient';
import { useAuthStore } from '../../store/authStore';
import { FileUpload } from '../../components/media/FileUpload';
import { Badge, Button, Card, Dialog, EmptyState, ErrorState, Field, InlineNotice, Input, MetricCard, Page, PageHeader, Select, Skeleton, Textarea } from '../../components/ui';

const DAYS = ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'];
const statusMeta = {
  PROFILE_ONLY: ['Chỉ có hồ sơ', 'neutral'],
  INVITED: ['Đã gửi lời mời', 'info'],
  ACTIVE: ['Hoạt động', 'success'],
  LOCKED: ['Đã khóa', 'danger'],
  ON_LEAVE: ['Nghỉ phép', 'warning'],
  INACTIVE: ['Đã ngừng làm việc', 'danger'],
};
const toTime = (value, fallback = '09:00') => { if (!value) return fallback; if (/^\d{2}:\d{2}/.test(value)) return value.slice(0, 5); const date = new Date(value); return Number.isNaN(date.getTime()) ? fallback : date.toISOString().slice(11, 16); };
const localDateTime = (value) => value ? new Date(value).toLocaleString('vi-VN') : '—';

function StaffCard({ staff, capabilities, onView, onEdit, onHours, onExceptions, onServices, onDeactivate }) {
  const [label, tone] = statusMeta[staff.status] || [staff.status || '—', 'neutral'];
  return <Card className="min-w-0 flex min-h-72 flex-col p-5">
    <div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-pink-50 text-lg font-bold text-pink-700" aria-hidden="true">{staff.fullName?.slice(0, 1).toUpperCase() || '?'}</span><div className="min-w-0 flex-1"><h2 className="truncate font-bold text-[var(--bb-ink)]">{staff.fullName}</h2><p className="mt-0.5 text-sm text-[var(--bb-muted)]">{staff.position || 'Nhân viên'}</p><p className="mt-0.5 truncate text-xs text-[var(--bb-muted)]">{staff.branch?.name || '—'}</p></div><Badge tone={tone}>{label}</Badge></div>
    <div className="mt-3 flex flex-wrap gap-2"><Badge tone={staff.isBookable ? 'success' : 'neutral'}>{staff.isBookable ? 'Nhận lịch' : 'Không nhận lịch'}</Badge>{staff.publicVisible ? <Badge tone="info">Hồ sơ công khai</Badge> : null}</div>
    <div className="mt-4 flex flex-wrap gap-1.5">{DAYS.map((day, index) => { const hour = staff.workingHours?.find((item) => item.dayOfWeek === index); const working = hour && !hour.isOff; return <span key={day} className={`grid h-7 w-7 place-items-center rounded text-[10px] font-bold ${working ? 'bg-pink-600 text-white' : 'bg-zinc-100 text-zinc-400'}`} title={working ? `${toTime(hour.startTime)}–${toTime(hour.endTime)}` : 'Nghỉ'}>{day}</span>; })}</div>
    <p className="mt-4 break-all text-xs text-[var(--bb-muted)]">{staff.services?.length || 0} dịch vụ{staff.user?.email ? ` · ${staff.user.email}` : ''}</p>
    <div className="mt-auto flex flex-wrap gap-2 border-t border-[var(--bb-border)] pt-4">{capabilities.readSchedule && <Button size="sm" onClick={() => onView(staff)}><UserCog size={14} />Chi tiết</Button>}{capabilities.manageSchedule && <Button size="sm" variant="secondary" onClick={() => onHours(staff)}><Clock3 size={14} />Chỉnh lịch định kỳ</Button>}{capabilities.manageStaff && <Button size="sm" variant="secondary" onClick={() => onEdit(staff)}><Pencil size={14} />Hồ sơ</Button>}{capabilities.readSchedule && <Button size="sm" variant="secondary" onClick={() => onExceptions(staff)}>Nghỉ & ngoại lệ</Button>}{capabilities.manageServices && <Button size="sm" variant="secondary" onClick={() => onServices(staff)}><Scissors size={14} />Dịch vụ</Button>}{capabilities.manageStaff && staff.status === 'ACTIVE' && <Button size="sm" variant="ghost" className="text-[var(--bb-danger)]" onClick={() => onDeactivate(staff)}><ShieldX size={14} />Khóa</Button>}</div>
  </Card>;
}

function StaffTable({ staff, capabilities, onView, onEdit, onHours, onExceptions, onServices, onDeactivate }) {
  return <Card className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-xs uppercase tracking-wide text-[var(--bb-muted)]"><tr><th className="px-4 py-3">Nhân viên</th><th className="px-4 py-3">Chi nhánh</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3">Dịch vụ</th><th className="px-4 py-3">Lịch làm</th><th className="px-4 py-3">Hành động</th></tr></thead><tbody className="divide-y divide-[var(--bb-border)]">{staff.map((item) => { const [label, tone] = statusMeta[item.status] || [item.status || '—', 'neutral']; const workingDays = item.workingHours?.filter((hour) => !hour.isOff).length || 0; return <tr key={item.id} className="align-top"><td className="px-4 py-4"><p className="font-bold">{item.fullName}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{item.position || 'Nhân viên'}{item.user?.email ? ` · ${item.user.email}` : ''}</p></td><td className="px-4 py-4">{item.branch?.name || '—'}</td><td className="px-4 py-4"><Badge tone={tone}>{label}</Badge></td><td className="px-4 py-4">{item.services?.length || 0}</td><td className="px-4 py-4">{workingDays}/7 ngày</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{capabilities.readSchedule && <Button size="sm" onClick={() => onView(item)}><UserCog size={14} />Chi tiết</Button>}{capabilities.manageSchedule && <Button size="sm" variant="secondary" onClick={() => onHours(item)}><Clock3 size={14} />Chỉnh lịch định kỳ</Button>}{capabilities.manageStaff && <Button size="sm" variant="secondary" onClick={() => onEdit(item)}><Pencil size={14} />Hồ sơ</Button>}{capabilities.readSchedule && <Button size="sm" variant="secondary" onClick={() => onExceptions(item)}>Ngoại lệ</Button>}{capabilities.manageServices && <Button size="sm" variant="secondary" onClick={() => onServices(item)}><Scissors size={14} />Dịch vụ</Button>}{capabilities.manageStaff && item.status === 'ACTIVE' && <Button size="sm" variant="ghost" className="text-[var(--bb-danger)]" onClick={() => onDeactivate(item)}><ShieldX size={14} />Khóa</Button>}</div></td></tr>; })}</tbody></table></Card>;
}

function StaffForm({ modal, branches, onClose, onSaved }) {
  const editing = Boolean(modal?.id);
  const [form, setForm] = useState({ branchId: '', fullName: '', position: '', bio: '', status: 'PROFILE_ONLY', isBookable: false, publicVisible: false, accountMode: 'LATER', email: '', roleCode: 'STAFF' });
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState({});
  const [portfolio, setPortfolio] = useState(null);
  useEffect(() => { if (modal === null) return; setForm({ branchId: modal?.branchId || branches[0]?.id || '', fullName: modal?.fullName || '', position: modal?.position || '', bio: modal?.bio || '', status: modal?.status || 'PROFILE_ONLY', isBookable: modal?.isBookable ?? false, publicVisible: modal?.publicVisible ?? false, accountMode: 'LATER', email: '', roleCode: 'STAFF' }); setPortfolio(modal?.images?.[0]?.media || null); setErrors({}); }, [modal, branches]);
  const set = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); const next = {}; if (!form.fullName.trim()) next.fullName = 'Nhập họ tên.'; if (!editing && !form.branchId) next.branchId = 'Chọn chi nhánh.'; if (!editing && form.accountMode === 'INVITE' && !form.email.trim()) next.email = 'Nhập email nhận lời mời.'; setErrors(next); if (Object.keys(next).length) return; setSaving(true); try { const payload = { fullName: form.fullName.trim(), position: form.position.trim(), bio: form.bio.trim(), isBookable: form.isBookable, publicVisible: form.publicVisible, ...(editing ? { status: form.status } : { branchId: form.branchId }) }; if (editing) { await staffApi.update(modal.id, payload); } else { const profile = await staffApi.create(payload); if (form.accountMode === 'INVITE') { const selectedBranch = branches.find((item) => item.id === form.branchId); await staffApi.invite({ staffProfileId: profile.id, email: form.email.trim(), roleCode: form.roleCode, businessId: selectedBranch.businessId, branchId: form.branchId }); } } toast.success(editing ? 'Đã cập nhật nhân viên' : form.accountMode === 'INVITE' ? 'Đã tạo hồ sơ và gửi lời mời' : 'Đã lưu hồ sơ nhân sự'); onSaved(); } catch (error) { toast.error(error.message || 'Không thể lưu nhân viên'); } finally { setSaving(false); } };
  return <Dialog open={modal !== null} onClose={onClose} title={editing ? 'Sửa hồ sơ nhân viên' : 'Thêm nhân sự'} description={editing ? 'Cập nhật hồ sơ nhân sự trong phạm vi chi nhánh được cấp.' : 'Một luồng duy nhất: tạo hồ sơ, chọn vai trò rồi cấp tài khoản ngay hoặc để sau.'} footer={<><Button variant="secondary" onClick={onClose}>Hủy</Button><Button type="submit" form="staff-form" loading={saving}>Lưu</Button></>}>
    <form id="staff-form" onSubmit={submit} className="grid gap-4">
      {editing && <FileUpload entityType="STAFF_IMAGE" entityId={modal.id} businessId={modal.branch?.businessId} branchId={modal.branch?.id} value={portfolio} label="Ảnh chuyên môn / portfolio" onUploaded={setPortfolio} onRemoved={() => setPortfolio(null)} />}
      {!editing && <Field label="Chi nhánh" required error={errors.branchId}><Select value={form.branchId} onChange={set('branchId')}><option value="">Chọn chi nhánh</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></Field>}
      <Field label="Họ tên" required error={errors.fullName}><Input autoFocus value={form.fullName} onChange={set('fullName')} /></Field>
      <Field label="Vị trí"><Input value={form.position} onChange={set('position')} placeholder="Chuyên viên spa" /></Field>
      <Field label="Giới thiệu"><Textarea value={form.bio} onChange={set('bio')} /></Field>
      {!editing && <div className="grid gap-4 rounded-xl border border-[var(--bb-border)] p-4"><Field label="Cấp tài khoản"><Select value={form.accountMode} onChange={set('accountMode')}><option value="LATER">Để sau — chỉ tạo hồ sơ</option><option value="INVITE">Gửi lời mời qua email ngay</option></Select></Field>{form.accountMode === 'INVITE' && <><Field label="Email nhận lời mời" required error={errors.email}><Input type="email" autoComplete="email" value={form.email} onChange={set('email')} /></Field><Field label="Vai trò làm việc" required><Select value={form.roleCode} onChange={set('roleCode')}><option value="STAFF">Nhân viên dịch vụ</option><option value="RECEPTIONIST">Lễ tân</option><option value="BRANCH_MANAGER">Quản lý chi nhánh</option></Select></Field></>}</div>}
      <div className="grid gap-3 rounded-xl border border-[var(--bb-border)] p-4 sm:grid-cols-2">
        <label className="flex cursor-pointer items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={form.isBookable} onChange={(event) => setForm((value) => ({ ...value, isBookable: event.target.checked }))} /><span><strong className="block">Cho phép nhận lịch</strong><small className="mt-1 block leading-5 text-[var(--bb-muted)]">Chỉ bật khi người này trực tiếp thực hiện dịch vụ.</small></span></label>
        <label className="flex cursor-pointer items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={form.publicVisible} disabled={!form.isBookable} onChange={(event) => setForm((value) => ({ ...value, publicVisible: event.target.checked }))} /><span><strong className="block">Hiện trên trang công khai</strong><small className="mt-1 block leading-5 text-[var(--bb-muted)]">Hồ sơ chỉ xuất hiện khi đã bật nhận lịch, có dịch vụ và lịch làm.</small></span></label>
      </div>
      {editing && <Field label="Trạng thái"><Select value={form.status} onChange={set('status')}><option value="PROFILE_ONLY">Chỉ có hồ sơ</option><option value="INVITED">Đã gửi lời mời</option><option value="ACTIVE">Hoạt động</option><option value="LOCKED">Đã khóa</option><option value="ON_LEAVE">Nghỉ phép</option><option value="INACTIVE">Đã ngừng làm việc</option></Select></Field>}
      <p className="text-xs leading-5 text-[var(--bb-muted)]">{modal?.userId || modal?.user ? 'Hồ sơ đã liên kết tài khoản đăng nhập.' : 'Chưa có tài khoản đăng nhập; việc tạo hồ sơ không tự cấp mật khẩu hoặc vai trò.'}</p>
    </form>
  </Dialog>;
}

function InviteForm({ open, branches, onClose, onSent }) {
  const [form, setForm] = useState({ email: '', roleCode: 'STAFF', branchId: '' });
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) setForm({ email: '', roleCode: 'STAFF', branchId: branches[0]?.id || '' }); }, [open, branches]);
  const submit = async (event) => { event.preventDefault(); const branch = branches.find((item) => item.id === form.branchId); if (!branch?.businessId) return toast.error('Chi nhánh chưa có businessId hợp lệ'); setSaving(true); try { await staffApi.invite({ ...form, email: form.email.trim(), businessId: branch.businessId }); toast.success('Đã gửi lời mời nhân viên'); onSent(); } catch (error) { toast.error(error.message || 'Không thể gửi lời mời'); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title="Mời nhân viên" description="Người nhận dùng email này để chấp nhận lời mời và vào đúng doanh nghiệp/chi nhánh." footer={<><Button variant="secondary" onClick={onClose}>Hủy</Button><Button type="submit" form="invite-staff" loading={saving}>Gửi lời mời</Button></>}><form id="invite-staff" onSubmit={submit} className="grid gap-4"><Field label="Email" required><Input type="email" autoComplete="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></Field><Field label="Vai trò" required><Select value={form.roleCode} onChange={(event) => setForm({ ...form, roleCode: event.target.value })}><option value="STAFF">Nhân viên</option><option value="RECEPTIONIST">Lễ tân</option><option value="BRANCH_MANAGER">Quản lý chi nhánh</option></Select></Field><Field label="Chi nhánh" required><Select required value={form.branchId} onChange={(event) => setForm({ ...form, branchId: event.target.value })}><option value="">Chọn chi nhánh</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></Field></form></Dialog>;
}

function WorkingHours({ staff, onClose, onSaved }) {
  const [days, setDays] = useState([]);
  const [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10));
  const [effectiveTo, setEffectiveTo] = useState('');
  const [note, setNote] = useState('');
  const [versions, setVersions] = useState([]);
  const [conflict, setConflict] = useState(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    if (!staff) return;
    setLoading(true);
    Promise.all([
      staffApi.getScheduleVersions(staff.id, staff.branch?.id),
      staffApi.getWorkingHours(staff.id),
    ]).then(([versionRows, legacyRows]) => {
      const versionList = Array.isArray(versionRows) ? versionRows : [];
      setVersions(versionList);
      const latest = versionList[0];
      if (latest) {
        setEffectiveFrom(new Date().toISOString().slice(0, 10));
        setNote(`Tạo từ phiên bản ${latest.version}`);
      }
      const segments = latest?.segments || (Array.isArray(legacyRows) ? legacyRows.filter((item) => !item.isOff).map((item) => ({ ...item, startTime: toTime(item.startTime), endTime: toTime(item.endTime, '18:00') })) : []);
      setDays(DAYS.map((_, dayOfWeek) => {
        const ranges = segments.filter((item) => item.dayOfWeek === dayOfWeek).map((item) => ({ startTime: toTime(item.startTime), endTime: toTime(item.endTime, '18:00') }));
        return { dayOfWeek, working: ranges.length > 0, ranges: ranges.length ? ranges : [{ startTime: '09:00', endTime: '18:00' }] };
      }));
      setConflict(null);
    }).catch((error) => toast.error(error.message || 'Không thể tải lịch định kỳ')).finally(() => setLoading(false));
  }, [staff]);
  const updateDay = (index, patch) => setDays((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const updateRange = (dayIndex, rangeIndex, patch) => setDays((rows) => rows.map((row, rowIndex) => rowIndex === dayIndex ? { ...row, ranges: row.ranges.map((range, itemIndex) => itemIndex === rangeIndex ? { ...range, ...patch } : range) } : row));
  const addRange = (index) => updateDay(index, { ranges: [...days[index].ranges, { startTime: '13:00', endTime: '18:00' }] });
  const removeRange = (dayIndex, rangeIndex) => updateDay(dayIndex, { ranges: days[dayIndex].ranges.filter((_, index) => index !== rangeIndex) });
  const preset = (lastDay) => setDays((current) => current.map((day) => ({ ...day, working: day.dayOfWeek >= 1 && day.dayOfWeek <= lastDay, ranges: [{ startTime: '09:00', endTime: '18:00' }] })));
  const save = async (acknowledge = false) => {
    const segments = days.flatMap((day) => day.working ? day.ranges.map((range, sortOrder) => ({ dayOfWeek: day.dayOfWeek, ...range, sortOrder })) : []);
    const invalid = !segments.length || segments.some((item) => item.startTime >= item.endTime);
    if (invalid) return toast.error('Lịch cần ít nhất một khung giờ hợp lệ');
    setSaving(true);
    try {
      await staffApi.saveScheduleVersion(staff.id, {
        branchId: staff.branch?.id,
        effectiveFrom,
        effectiveTo: effectiveTo || null,
        note,
        segments,
        acknowledgeImpact: acknowledge,
        acknowledgeOutOfHours: acknowledge,
      });
      toast.success('Đã lưu phiên bản lịch định kỳ mới');
      setConflict(null);
      onSaved();
    } catch (error) {
      const details = error.details;
      if (error.status === 409 && (details?.code || details?.message?.code)) {
        setConflict(details?.code ? details : details.message);
      } else toast.error(error.message || 'Không thể lưu lịch định kỳ');
    } finally {
      setSaving(false);
    }
  };
  return <Dialog open={Boolean(staff)} onClose={onClose} title="Lịch làm việc định kỳ" description={`${staff?.fullName || ''} · Lịch này lặp lại hàng tuần; booking, nghỉ phép, ngày đặc biệt và chấm công được áp dụng riêng.`} footer={<><Button variant="secondary" onClick={onClose}>Đóng</Button><Button loading={saving} onClick={() => save(false)}>Lưu phiên bản</Button></>}>
    {loading ? <Skeleton rows={7} /> : <div className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Áp dụng từ" required><Input type="date" required value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></Field><Field label="Kết thúc (tùy chọn)"><Input type="date" min={effectiveFrom} value={effectiveTo} onChange={(event) => setEffectiveTo(event.target.value)} /></Field><Field label="Chi nhánh"><Input disabled value={staff?.branch?.name || ''} /></Field></div>
      <Field label="Ghi chú phiên bản"><Input value={note} onChange={(event) => setNote(event.target.value)} /></Field>
      <div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => preset(5)}>Preset T2–T6</Button><Button size="sm" variant="secondary" onClick={() => preset(6)}>Preset T2–T7</Button><Button size="sm" variant="secondary" onClick={() => setDays((current) => current.map((day) => ({ ...day, working: true })))}>Tất cả ngày</Button>{versions[0] && <Badge>Phiên bản hiện tại: v{versions[0].version}</Badge>}</div>
      {conflict && <InlineNotice tone="warning"><strong>{conflict.message || 'Lịch mới cần xác nhận'}</strong>{conflict.count ? <p className="mt-1">{conflict.count} booking bị ảnh hưởng; hệ thống không tự hủy hoặc reassign.</p> : null}<Button className="mt-3" size="sm" onClick={() => save(true)} loading={saving}>Tôi đã xem cảnh báo, lưu phiên bản</Button></InlineNotice>}
      <div className="max-h-[54vh] space-y-2 overflow-y-auto pr-1">{days.map((day, dayIndex) => <div key={day.dayOfWeek} className="rounded-xl border border-[var(--bb-border)] p-3"><div className="flex items-center gap-3"><strong className="w-10 text-sm">{DAYS[day.dayOfWeek]}</strong><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={day.working} onChange={(event) => updateDay(dayIndex, { working: event.target.checked })} />Làm việc</label></div>{day.working && <div className="mt-3 space-y-2">{day.ranges.map((range, rangeIndex) => <div key={`${day.dayOfWeek}-${rangeIndex}`} className="grid grid-cols-[1fr_1fr_auto] gap-2"><Input aria-label={`Bắt đầu ${DAYS[day.dayOfWeek]}`} type="time" value={range.startTime} onChange={(event) => updateRange(dayIndex, rangeIndex, { startTime: event.target.value })} /><Input aria-label={`Kết thúc ${DAYS[day.dayOfWeek]}`} type="time" value={range.endTime} onChange={(event) => updateRange(dayIndex, rangeIndex, { endTime: event.target.value })} /><Button size="sm" variant="ghost" disabled={day.ranges.length === 1} onClick={() => removeRange(dayIndex, rangeIndex)}>Gỡ</Button></div>)}<Button size="sm" variant="secondary" onClick={() => addRange(dayIndex)}>Thêm khung giờ</Button></div>}</div>)}</div>
    </div>}
  </Dialog>;
}

function ServiceAssignment({ staff, onClose, onSaved }) {
  const [services, setServices] = useState([]); const [selected, setSelected] = useState(new Set()); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!staff) return; setSelected(new Set(staff.services?.map((item) => item.id) || [])); setLoading(true); servicesApi.getManage().then((data) => setServices(Array.isArray(data) ? data : data?.data || [])).catch((error) => toast.error(error.message || 'Không thể tải dịch vụ')).finally(() => setLoading(false)); }, [staff]);
  const toggle = (id) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const save = async () => { setSaving(true); try { await staffApi.assignServices(staff.id, [...selected]); toast.success('Đã cập nhật dịch vụ phụ trách'); onSaved(); } catch (error) { toast.error(error.message || 'Không thể gán dịch vụ'); } finally { setSaving(false); } };
  return <Dialog open={Boolean(staff)} onClose={onClose} title="Dịch vụ phụ trách" description={staff?.fullName} footer={<><Button variant="secondary" onClick={onClose}>Đóng</Button><Button loading={saving} onClick={save}>Lưu ({selected.size})</Button></>}>{loading ? <Skeleton rows={5} /> : services.length === 0 ? <EmptyState title="Chưa có dịch vụ" /> : <div className="space-y-2">{services.map((service) => <label key={service.id} className="flex cursor-pointer items-center gap-3 rounded-lg border border-[var(--bb-border)] p-3"><input type="checkbox" checked={selected.has(service.id)} onChange={() => toggle(service.id)} /><span className="min-w-0 flex-1"><strong className="block text-sm">{service.name}</strong><span className="text-xs text-[var(--bb-muted)]">{Number(service.price || 0).toLocaleString('vi-VN')} ₫ · {service.durationMinutes || service.duration || 0} phút</span></span></label>)}</div>}</Dialog>;
}

function ScheduleExceptions({ staff, canManage, onClose }) {
  const [data, setData] = useState({ breaks: [], leaves: [], holidays: [], specialDays: [] });
  const [breaks, setBreaks] = useState([]); const [newBreak, setNewBreak] = useState({ dayOfWeek: 1, startTime: '12:00', endTime: '13:00' }); const [leave, setLeave] = useState({ startAt: '', endAt: '', reason: '' }); const [holiday, setHoliday] = useState({ date: '', name: '', isClosed: true }); const [special, setSpecial] = useState({ date: '', startTime: '09:00', endTime: '18:00' }); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState('');
  const load = async () => { if (!staff) return; setLoading(true); try { const result = await staffApi.getScheduleExceptions(staff.id); setData(result || {}); setBreaks((result?.breaks || []).map((item) => ({ dayOfWeek: item.dayOfWeek, startTime: toTime(item.startTime, '12:00'), endTime: toTime(item.endTime, '13:00') }))); } catch (error) { toast.error(error.message || 'Không thể tải nghỉ và ngoại lệ'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [staff]);
  const action = async (key, callback, message) => { setBusy(key); try { await callback(); toast.success(message); await load(); } catch (error) { toast.error(error.message || 'Không thể thực hiện'); } finally { setBusy(''); } };
  const saveBreaks = () => { if (breaks.some((item) => item.startTime >= item.endTime)) return toast.error('Giờ nghỉ không hợp lệ'); action('breaks', () => staffApi.replaceBreaks(staff.id, breaks), 'Đã cập nhật giờ nghỉ'); };
  const requestLeave = () => { if (!leave.startAt || !leave.endAt || leave.startAt >= leave.endAt) return toast.error('Khoảng nghỉ không hợp lệ'); action('leave', () => staffApi.requestLeave(staff.id, leave), 'Đã tạo yêu cầu nghỉ').then?.(() => setLeave({ startAt: '', endAt: '', reason: '' })); };
  const addHoliday = () => { if (!holiday.date || !holiday.name.trim()) return toast.error('Nhập ngày và tên ngày nghỉ'); action('holiday', () => staffApi.upsertHoliday(staff.branchId, holiday), 'Đã cập nhật ngày đóng cửa'); };
  const addSpecial = () => { if (!special.date || special.startTime >= special.endTime) return toast.error('Ngày hoặc khung giờ không hợp lệ'); action('special', () => staffApi.createSpecialDay(staff.branchId, { ...special, staffId: staff.id }), 'Đã thêm ngày làm đặc biệt'); };
  return <Dialog open={Boolean(staff)} onClose={onClose} title="Nghỉ & ngoại lệ lịch" description={`${staff?.fullName || ''} · ${staff?.branch?.name || ''}`} size="xl">
    {loading ? <Skeleton rows={7} /> : <div className="grid gap-6 lg:grid-cols-2">
      <Card className="p-4"><h3 className="font-bold">Giờ nghỉ hàng tuần</h3><div className="mt-3 space-y-2">{breaks.map((item, index) => <div key={`${item.dayOfWeek}-${index}`} className="flex items-center gap-2 rounded-lg bg-[var(--bb-surface-subtle)] p-3 text-sm"><strong>{DAYS[item.dayOfWeek]}</strong><span>{item.startTime}–{item.endTime}</span>{canManage && <Button className="ml-auto" size="sm" variant="ghost" onClick={() => setBreaks((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}>Xóa</Button>}</div>)}{!breaks.length && <p className="text-sm text-[var(--bb-muted)]">Chưa có giờ nghỉ.</p>}</div>{canManage && <div className="mt-4 grid grid-cols-3 gap-2"><Select aria-label="Thứ" value={newBreak.dayOfWeek} onChange={(event) => setNewBreak({ ...newBreak, dayOfWeek: Number(event.target.value) })}>{DAYS.map((day, index) => <option key={day} value={index}>{day}</option>)}</Select><Input aria-label="Giờ bắt đầu nghỉ" type="time" value={newBreak.startTime} onChange={(event) => setNewBreak({ ...newBreak, startTime: event.target.value })} /><Input aria-label="Giờ kết thúc nghỉ" type="time" value={newBreak.endTime} onChange={(event) => setNewBreak({ ...newBreak, endTime: event.target.value })} /><div className="col-span-3 flex gap-2"><Button size="sm" variant="secondary" onClick={() => { if (newBreak.startTime >= newBreak.endTime) return toast.error('Giờ nghỉ không hợp lệ'); setBreaks((rows) => [...rows, { ...newBreak }]); }}>Thêm giờ nghỉ</Button><Button size="sm" loading={busy === 'breaks'} onClick={saveBreaks}>Lưu tất cả</Button></div></div>}</Card>
      <Card className="p-4"><h3 className="font-bold">Yêu cầu nghỉ</h3><div className="mt-3 max-h-52 space-y-2 overflow-y-auto">{(data.leaves || []).map((item) => <div key={item.id} className="rounded-lg bg-[var(--bb-surface-subtle)] p-3"><p className="text-sm font-semibold">{localDateTime(item.startAt)} → {localDateTime(item.endAt)}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{item.reason || 'Không có lý do'} · {item.status}</p>{canManage && item.status === 'PENDING' && <div className="mt-2 flex gap-2"><Button size="sm" variant="secondary" onClick={() => action(`approve-${item.id}`, () => staffApi.reviewLeave(item.id, true), 'Đã duyệt nghỉ')}>Duyệt</Button><Button size="sm" variant="ghost" onClick={() => action(`reject-${item.id}`, () => staffApi.reviewLeave(item.id, false), 'Đã từ chối nghỉ')}>Từ chối</Button></div>}</div>)}{!data.leaves?.length && <p className="text-sm text-[var(--bb-muted)]">Chưa có yêu cầu nghỉ.</p>}</div>{canManage && <div className="mt-4 grid gap-2"><Field label="Bắt đầu"><Input type="datetime-local" value={leave.startAt} onChange={(event) => setLeave({ ...leave, startAt: event.target.value })} /></Field><Field label="Kết thúc"><Input type="datetime-local" value={leave.endAt} onChange={(event) => setLeave({ ...leave, endAt: event.target.value })} /></Field><Field label="Lý do"><Input value={leave.reason} onChange={(event) => setLeave({ ...leave, reason: event.target.value })} /></Field><Button className="w-fit" size="sm" loading={busy === 'leave'} onClick={requestLeave}>Tạo yêu cầu</Button></div>}</Card>
      <Card className="p-4"><h3 className="font-bold">Ngày đóng cửa</h3><div className="mt-3 flex flex-wrap gap-2">{(data.holidays || []).map((item) => <Badge key={item.id} tone={item.isClosed ? 'danger' : 'neutral'}>{new Date(item.date).toLocaleDateString('vi-VN')} · {item.name}</Badge>)}{!data.holidays?.length && <p className="text-sm text-[var(--bb-muted)]">Chưa có ngày đóng cửa.</p>}</div>{canManage && <div className="mt-4 grid gap-2 sm:grid-cols-2"><Field label="Ngày"><Input type="date" value={holiday.date} onChange={(event) => setHoliday({ ...holiday, date: event.target.value })} /></Field><Field label="Tên ngày nghỉ"><Input value={holiday.name} onChange={(event) => setHoliday({ ...holiday, name: event.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={holiday.isClosed} onChange={(event) => setHoliday({ ...holiday, isClosed: event.target.checked })} /> Đóng cửa cả ngày</label><Button className="w-fit" size="sm" loading={busy === 'holiday'} onClick={addHoliday}>Lưu ngày nghỉ</Button></div>}</Card>
      <Card className="p-4"><h3 className="font-bold">Lịch làm đặc biệt</h3><p className="mt-1 text-xs leading-5 text-[var(--bb-muted)]">Dùng khi nhân viên làm thêm hoặc làm khác lịch cố định trong một ngày cụ thể.</p><div className="mt-3 flex flex-wrap gap-2">{(data.specialDays || []).map((item) => <Badge key={item.id} tone="info">{new Date(item.date).toLocaleDateString('vi-VN')} · {toTime(item.startTime)}–{toTime(item.endTime)}</Badge>)}{!data.specialDays?.length && <p className="text-sm text-[var(--bb-muted)]">Chưa có lịch làm đặc biệt.</p>}</div>{canManage && <div className="mt-4 grid gap-2 sm:grid-cols-3"><Field label="Ngày"><Input type="date" value={special.date} onChange={(event) => setSpecial({ ...special, date: event.target.value })} /></Field><Field label="Bắt đầu"><Input type="time" value={special.startTime} onChange={(event) => setSpecial({ ...special, startTime: event.target.value })} /></Field><Field label="Kết thúc"><Input type="time" value={special.endTime} onChange={(event) => setSpecial({ ...special, endTime: event.target.value })} /></Field><Button className="w-fit sm:col-span-3" size="sm" loading={busy === 'special'} onClick={addSpecial}>Thêm lịch đặc biệt</Button></div>}</Card>
    </div>}
  </Dialog>;
}

export function SalonStaffManagement() {
  const navigate = useNavigate();
  const can = useAuthStore((state) => state.can);
  const capabilities = { manageStaff: can('user:role_assign:tenant') || can('user:role_assign:branch') || can('user:role_assign:platform'), readSchedule: can('staff_schedule:read:branch') || can('staff_schedule:read:self') || can('staff_schedule:manage:branch'), manageSchedule: can('staff_schedule:manage:branch'), manageServices: can('staff_service:assign:tenant') || can('staff_service:assign:branch') };
  const [staff, setStaff] = useState([]); const [branches, setBranches] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL'); const [branch, setBranch] = useState('ALL'); const [view, setView] = useState('grid'); const [editor, setEditor] = useState(null); const [hours, setHours] = useState(null); const [exceptions, setExceptions] = useState(null); const [services, setServices] = useState(null); const [deactivate, setDeactivate] = useState(null); const [offboardingReason, setOffboardingReason] = useState(''); const [offboardingImpact, setOffboardingImpact] = useState(null); const [acknowledgeImpact, setAcknowledgeImpact] = useState(false); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const [staffData, branchData] = await Promise.all([staffApi.getAll(), branchesApi.getAccessible()]); setStaff(Array.isArray(staffData) ? staffData : staffData?.data || []); setBranches(Array.isArray(branchData) ? branchData : branchData?.data || []); } catch (loadError) { setError(loadError.message || 'Không thể tải dữ liệu nhân sự.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => staff.filter((item) => { const query = search.trim().toLocaleLowerCase('vi'); return (!query || item.fullName?.toLocaleLowerCase('vi').includes(query) || item.position?.toLocaleLowerCase('vi').includes(query)) && (status === 'ALL' || item.status === status) && (branch === 'ALL' || item.branchId === branch || item.branch?.id === branch); }), [staff, search, status, branch]);
  const openDeactivate = async (selected) => { setDeactivate(selected); setOffboardingReason(''); setAcknowledgeImpact(false); setOffboardingImpact(null); try { setOffboardingImpact(await staffApi.getOffboardingImpact(selected.id)); } catch (error) { toast.error(error.message || 'Không thể tải ảnh hưởng offboarding'); } };
  const deactivateStaff = async () => { if (!deactivate) return; if (!offboardingReason.trim()) return toast.error('Nhập lý do ngừng làm việc'); if (offboardingImpact?.requiresReassignment && !acknowledgeImpact) return toast.error('Xác nhận đã có kế hoạch xử lý lịch tương lai'); setBusy(true); try { await staffApi.deactivate(deactivate.id, { reason: offboardingReason.trim(), acknowledgeFutureBookings: acknowledgeImpact }); toast.success('Đã ngừng quyền làm việc; tài khoản khách hàng vẫn được giữ'); setDeactivate(null); await load(); } catch (error) { toast.error(error.message || 'Không thể ngừng nhân sự'); } finally { setBusy(false); } };
  const closeAndReload = (setter) => async () => { setter(null); await load(); };
  return <Page>
    <PageHeader eyebrow="Vận hành chi nhánh" title="Nhân sự" description="Hồ sơ, lời mời, lịch làm, giờ nghỉ, nghỉ phép, ngoại lệ và dịch vụ phụ trách trong đúng scope được cấp." actions={capabilities.manageStaff && <Button onClick={() => setEditor({})}><Plus size={17} />Thêm nhân sự</Button>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Users} label="Tổng nhân viên" value={staff.length} /><MetricCard icon={UserCog} label="Đang hoạt động" value={staff.filter((item) => item.status === 'ACTIVE').length} tone="success" /><MetricCard icon={CalendarDays} label="Nghỉ phép" value={staff.filter((item) => item.status === 'ON_LEAVE').length} tone="warning" /><MetricCard icon={ShieldX} label="Tạm ngưng nhận lịch" value={staff.filter((item) => item.status === 'INACTIVE').length} tone="neutral" /></div>
    <Card className="p-4"><div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_190px_220px_auto]"><Field label="Tìm nhân viên"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-[var(--bb-muted)]" size={16} /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tên hoặc vị trí" /></div></Field><Field label="Trạng thái"><Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">Tất cả</option><option value="PROFILE_ONLY">Chỉ có hồ sơ</option><option value="INVITED">Đã gửi lời mời</option><option value="ACTIVE">Hoạt động</option><option value="LOCKED">Đã khóa</option><option value="ON_LEAVE">Nghỉ phép</option><option value="INACTIVE">Đã ngừng làm việc</option></Select></Field><Field label="Chi nhánh"><Select value={branch} onChange={(event) => setBranch(event.target.value)}><option value="ALL">Tất cả chi nhánh</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><div className="flex items-end"><div className="flex rounded-xl border border-[var(--bb-border)] p-1"><Button size="icon" variant={view === 'grid' ? 'primary' : 'ghost'} aria-label="Xem dạng thẻ" onClick={() => setView('grid')}><LayoutGrid size={17} /></Button><Button size="icon" variant={view === 'table' ? 'primary' : 'ghost'} aria-label="Xem dạng bảng" onClick={() => setView('table')}><List size={17} /></Button></div></div></div></Card>
    {loading ? <Card className="p-5"><Skeleton rows={7} /></Card> : error ? <Card><ErrorState message={error} onRetry={load} /></Card> : filtered.length === 0 ? <Card><EmptyState icon={Users} title="Không có nhân viên phù hợp" description={staff.length ? 'Thử đổi bộ lọc.' : 'Chưa có nhân viên trong phạm vi được cấp.'} action={capabilities.manageStaff && !staff.length ? <Button onClick={() => setEditor({})}>Thêm nhân viên</Button> : null} /></Card> : view === 'grid' ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <StaffCard key={item.id} staff={item} capabilities={capabilities} onView={(selected) => navigate(`/salon/staff/${selected.id}`)} onEdit={setEditor} onHours={setHours} onExceptions={setExceptions} onServices={setServices} onDeactivate={openDeactivate} />)}</div> : <StaffTable staff={filtered} capabilities={capabilities} onView={(selected) => navigate(`/salon/staff/${selected.id}`)} onEdit={setEditor} onHours={setHours} onExceptions={setExceptions} onServices={setServices} onDeactivate={openDeactivate} />}
    <StaffForm modal={editor} branches={branches} onClose={() => setEditor(null)} onSaved={closeAndReload(setEditor)} /><WorkingHours staff={hours} onClose={() => setHours(null)} onSaved={closeAndReload(setHours)} /><ServiceAssignment staff={services} onClose={() => setServices(null)} onSaved={closeAndReload(setServices)} /><ScheduleExceptions staff={exceptions} canManage={capabilities.manageSchedule} onClose={() => setExceptions(null)} />
    <Dialog open={Boolean(deactivate)} onClose={() => setDeactivate(null)} title="Ngừng quyền làm việc?" description={deactivate?.fullName} footer={<><Button variant="secondary" onClick={() => setDeactivate(null)}>Hủy</Button><Button variant="danger" loading={busy} onClick={deactivateStaff}>Xác nhận ngừng làm việc</Button></>}><div className="space-y-4"><InlineNotice tone="warning">Hồ sơ và lịch sử được giữ nguyên. Chỉ role/membership và phiên SALON của doanh nghiệp này bị thu hồi; quyền Customer không bị ảnh hưởng.</InlineNotice><Field label="Lý do" required><Textarea value={offboardingReason} onChange={(event) => setOffboardingReason(event.target.value)} /></Field>{offboardingImpact?.futureBookingCount > 0 && <label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><input className="mt-1" type="checkbox" checked={acknowledgeImpact} onChange={(event) => setAcknowledgeImpact(event.target.checked)} /><span><strong>{offboardingImpact.futureBookingCount} lịch tương lai cần phân công lại</strong><small className="mt-1 block">Tôi đã xem danh sách ảnh hưởng và có kế hoạch xử lý; hệ thống không tự hủy lịch.</small></span></label>}</div></Dialog>
  </Page>;
}

export default SalonStaffManagement;
