import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, Clock3, MapPin, Search, UserRound } from 'lucide-react';
import toast from 'react-hot-toast';
import { bookingsApi, servicesApi } from '../../../api/apiClient';
import { BOOKING_STATUSES, BOOKING_STATUS_LIST, labelToEnum } from '../../../constants/status';
import { useAuthStore } from '../../../store/authStore';
import { Badge, Button, Card, Dialog, EmptyState, ErrorState, Field, Input, Select, Skeleton } from '../../ui';

const toneByStatus = { PENDING: 'warning', CONFIRMED: 'info', CHECKED_IN: 'info', IN_PROGRESS: 'brand', COMPLETED: 'success', CANCELLED: 'danger', NO_SHOW: 'neutral' };
const asDate = (value) => value ? new Date(value).toLocaleDateString('vi-VN') : '—';
const asTime = (value) => value ? new Date(value).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) : '—';
const statusInfo = (value) => { const code = BOOKING_STATUSES[value] ? value : labelToEnum(value); return { code, label: BOOKING_STATUSES[code]?.label || value || '—', tone: toneByStatus[code] || 'neutral' }; };

function BookingDialog({ booking, canUpdate, onClose, onUpdated }) {
  const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (booking) setStatus(statusInfo(booking.status).code); }, [booking]);
  const update = async () => { if (!booking || !status) return; setSaving(true); try { await bookingsApi.updateStatus(booking.bookingId || booking.id, status); toast.success('Đã cập nhật trạng thái'); onUpdated(); } catch (error) { toast.error(error.message || 'Không thể cập nhật trạng thái'); } finally { setSaving(false); } };
  return <Dialog open={Boolean(booking)} onClose={onClose} title="Chi tiết lịch hẹn" description={booking?.id} footer={<><Button variant="secondary" onClick={onClose}>Đóng</Button>{canUpdate && <Button loading={saving} disabled={status === statusInfo(booking?.status).code} onClick={update}>Lưu trạng thái</Button>}</>}>
    {booking && <div className="space-y-4"><Card className="bg-[var(--bb-surface-subtle)] p-4"><code className="font-bold">{booking.id}</code><Badge className="ml-2" tone={statusInfo(booking.status).tone}>{statusInfo(booking.status).label}</Badge></Card><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-[var(--bb-muted)]">Khách hàng</dt><dd className="mt-1 text-sm font-semibold">{booking.customer_name || '—'}</dd><dd className="text-sm text-[var(--bb-muted)]">{booking.customer_phone || 'Không có số điện thoại'}</dd></div><div><dt className="text-xs font-bold uppercase text-[var(--bb-muted)]">Ngày giờ</dt><dd className="mt-1 text-sm font-semibold">{asDate(booking.appointment_time)}</dd><dd className="text-sm text-[var(--bb-muted)]">{asTime(booking.appointment_start)} – {asTime(booking.appointment_end)}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-[var(--bb-muted)]">Cơ sở</dt><dd className="mt-1 text-sm">{booking.salon_name || '—'} · {booking.branch_name || '—'}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-[var(--bb-muted)]">Dịch vụ</dt><dd className="mt-2 space-y-2">{booking.services?.length ? booking.services.map((service, index) => <div key={`${service.name}-${index}`} className="flex justify-between rounded-lg bg-[var(--bb-surface-subtle)] p-3 text-sm"><span>{service.name}</span><span className="text-[var(--bb-muted)]">{service.duration || 0} phút</span></div>) : <span className="text-sm text-[var(--bb-muted)]">{booking.service_category || '—'}</span>}</dd></div>{booking.note && <div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-[var(--bb-muted)]">Ghi chú</dt><dd className="mt-1 text-sm">{booking.note}</dd></div>}</dl>{canUpdate && <Field label="Cập nhật trạng thái"><Select value={status} onChange={(event) => setStatus(event.target.value)}>{BOOKING_STATUS_LIST.map((item) => <option key={item.enum} value={item.enum}>{item.label}</option>)}</Select></Field>}</div>}
  </Dialog>;
}

export default function SchedulerListView({ branchId, branchIds = [], zone = 'salon' }) {
  const can = useAuthStore((state) => state.can);
  const emptyFilters = { search: '', customerQuery: '', status: '', categoryId: '', serviceId: '', source: '', dateFrom: '', dateTo: '' };
  const [bookings, setBookings] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [pagination, setPagination] = useState({ page: 1, totalPages: 1, total: 0 }); const [draft, setDraft] = useState(emptyFilters); const [filters, setFilters] = useState(emptyFilters); const [selected, setSelected] = useState(null); const [categories, setCategories] = useState([]); const [services, setServices] = useState([]);
  const canUpdate = can('booking:update:branch') || can('booking:update:tenant') || can('booking:update:platform');
  const load = useCallback(async () => { if (!branchId && branchIds.length === 0) return; setLoading(true); setError(''); try { const response = await bookingsApi.getAll({ ...filters, branchId, branchIds: branchId ? undefined : branchIds.join(','), page: pagination.page, limit: 20 }); setBookings(response.data || []); setPagination((current) => ({ ...current, page: response.meta?.page || current.page, totalPages: response.meta?.totalPages || 1, total: response.meta?.total || 0 })); } catch (loadError) { setError(loadError.message || 'Không thể tải danh sách lịch hẹn.'); } finally { setLoading(false); } }, [branchId, branchIds, filters, pagination.page]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (zone !== 'admin') return; Promise.all([servicesApi.getCategories(), servicesApi.getAll(branchId)]).then(([categoryRows, serviceRows]) => { setCategories(Array.isArray(categoryRows) ? categoryRows : []); setServices(Array.isArray(serviceRows) ? serviceRows : serviceRows?.data || []); }).catch(() => { setCategories([]); setServices([]); }); }, [branchId, zone]);
  const apply = (event) => { event.preventDefault(); setPagination((value) => ({ ...value, page: 1 })); setFilters(draft); };
  return <div className="h-full overflow-y-auto bg-[var(--bb-canvas)] p-4 sm:p-5">
    <Card className="p-4"><form onSubmit={apply} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field label="Mã lịch"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-[var(--bb-muted)]" size={16} /><Input className="pl-9" value={draft.search} onChange={(event) => setDraft({ ...draft, search: event.target.value })} placeholder="Mã lịch" /></div></Field>{zone === 'admin' && <Field label="Khách hàng / người dùng"><Input value={draft.customerQuery} onChange={(event) => setDraft({ ...draft, customerQuery: event.target.value })} placeholder="Tên, email hoặc điện thoại" /></Field>}<Field label="Trạng thái"><Select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="">Tất cả</option>{BOOKING_STATUS_LIST.map((item) => <option key={item.enum} value={item.enum}>{item.label}</option>)}</Select></Field>{zone === 'admin' && <Field label="Nhóm dịch vụ"><Select value={draft.categoryId} onChange={(event) => setDraft({ ...draft, categoryId: event.target.value, serviceId: '' })}><option value="">Tất cả nhóm</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}{zone === 'admin' && <Field label="Dịch vụ"><Select value={draft.serviceId} onChange={(event) => setDraft({ ...draft, serviceId: event.target.value })}><option value="">Tất cả dịch vụ</option>{services.filter((item) => !draft.categoryId || item.categoryId === draft.categoryId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}{zone === 'admin' && <Field label="Nguồn đặt"><Select value={draft.source} onChange={(event) => setDraft({ ...draft, source: event.target.value })}><option value="">Tất cả nguồn</option>{['ONLINE_WEB','WALK_IN','PHONE','STAFF_CREATED','ADMIN_CREATED'].map((value) => <option key={value} value={value}>{value}</option>)}</Select></Field>}<Field label="Từ ngày"><Input type="date" value={draft.dateFrom} onChange={(event) => setDraft({ ...draft, dateFrom: event.target.value })} /></Field><Field label="Đến ngày"><Input type="date" value={draft.dateTo} onChange={(event) => setDraft({ ...draft, dateTo: event.target.value })} /></Field><div className="flex items-end gap-2"><Button type="submit" variant="secondary">Áp dụng</Button><Button type="button" variant="ghost" onClick={() => { setDraft(emptyFilters); setFilters(emptyFilters); }}>Xóa lọc</Button></div></form></Card>
    {zone === 'admin' && !loading && bookings.length > 0 && <div className="mt-4 hidden overflow-x-auto rounded-xl border border-[var(--bb-border)] bg-white md:block"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-left text-xs text-[var(--bb-muted)]"><tr><th className="p-3">Mã lịch / khách</th><th className="p-3">Cơ sở / chi nhánh</th><th className="p-3">Nhóm / dịch vụ / nhân viên</th><th className="p-3">Thời gian</th><th className="p-3">Nguồn</th><th className="p-3">Tổng tiền</th><th className="p-3">Trạng thái</th></tr></thead><tbody>{bookings.map((booking) => { const info = statusInfo(booking.statusEnum || booking.status); return <tr key={`admin-${booking.bookingId || booking.id}`} className="cursor-pointer border-t border-[var(--bb-border)] hover:bg-pink-50/40" onClick={() => setSelected(booking)}><td className="p-3"><code className="font-bold">{booking.id}</code><strong className="block">{booking.customer_name}</strong><span className="text-xs text-[var(--bb-muted)]">{booking.customer_phone}</span></td><td className="p-3">{booking.salon_name}<span className="block text-xs text-[var(--bb-muted)]">{booking.branch_name}</span></td><td className="p-3">{booking.service_category}<span className="block text-xs text-[var(--bb-muted)]">{booking.services?.map((item) => `${item.name}${item.staff ? ` · ${item.staff}` : ''}`).join(', ')}</span></td><td className="p-3">{asDate(booking.appointment_time)}<span className="block text-xs">{asTime(booking.appointment_start)}–{asTime(booking.appointment_end)}</span></td><td className="p-3"><code>{booking.source || '—'}</code></td><td className="p-3 font-bold">{Number(booking.total_amount || 0).toLocaleString('vi-VN')}₫</td><td className="p-3"><Badge tone={info.tone}>{info.label}</Badge></td></tr>; })}</tbody></table></div>}
    <div className="mt-4">{loading ? <Card className="p-5"><Skeleton rows={8} /></Card> : error ? <Card><ErrorState message={error} onRetry={load} /></Card> : bookings.length === 0 ? <Card><EmptyState icon={CalendarDays} title="Không có lịch hẹn phù hợp" /></Card> : <><div className={`${zone === 'admin' ? 'hidden' : 'hidden md:block'} overflow-hidden rounded-[var(--bb-radius-card)] border border-[var(--bb-border)] bg-white`}><table className="w-full text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-xs text-[var(--bb-muted)]"><tr><th className="p-3 text-left">Mã lịch</th><th className="p-3 text-left">Khách hàng</th><th className="p-3 text-left">Dịch vụ</th><th className="p-3 text-left">Ngày giờ</th><th className="p-3 text-left">Trạng thái</th></tr></thead><tbody>{bookings.map((booking) => { const info = statusInfo(booking.status); return <tr key={booking.bookingId || booking.id} tabIndex="0" role="button" onClick={() => setSelected(booking)} onKeyDown={(event) => (event.key === 'Enter' || event.key === ' ') && setSelected(booking)} className="cursor-pointer border-t border-[var(--bb-border)] hover:bg-pink-50/40 focus:bg-pink-50"><td className="p-3"><code className="font-bold">{booking.id}</code></td><td className="p-3"><strong>{booking.customer_name}</strong><span className="block text-xs text-[var(--bb-muted)]">{booking.customer_phone}</span></td><td className="p-3">{booking.services?.[0]?.name || booking.service_category || '—'}{booking.services?.length > 1 && <span className="block text-xs text-[var(--bb-muted)]">+{booking.services.length - 1} dịch vụ</span>}</td><td className="p-3">{asDate(booking.appointment_time)}<span className="block text-xs text-[var(--bb-muted)]">{asTime(booking.appointment_start)}–{asTime(booking.appointment_end)}</span></td><td className="p-3"><Badge tone={info.tone}>{info.label}</Badge></td></tr>; })}</tbody></table></div><div className="space-y-3 md:hidden">{bookings.map((booking) => { const info = statusInfo(booking.status); return <button key={booking.bookingId || booking.id} onClick={() => setSelected(booking)} className="w-full rounded-[var(--bb-radius-card)] border border-[var(--bb-border)] bg-white p-4 text-left"><div className="flex items-start justify-between gap-2"><code className="font-bold">{booking.id}</code><Badge tone={info.tone}>{info.label}</Badge></div><p className="mt-3 flex items-center gap-2 text-sm font-semibold"><UserRound size={15} />{booking.customer_name}</p><p className="mt-2 flex items-center gap-2 text-xs text-[var(--bb-muted)]"><Clock3 size={14} />{asDate(booking.appointment_time)} · {asTime(booking.appointment_start)}</p><p className="mt-2 flex items-center gap-2 text-xs text-[var(--bb-muted)]"><MapPin size={14} />{booking.branch_name || '—'}</p></button>; })}</div></>}</div>
    {!loading && !error && pagination.totalPages > 1 && <nav className="mt-4 flex items-center justify-between" aria-label="Phân trang lịch hẹn"><span className="text-sm text-[var(--bb-muted)]">{bookings.length}/{pagination.total} lịch</span><div className="flex items-center gap-2"><Button size="sm" variant="secondary" disabled={pagination.page <= 1} onClick={() => setPagination((value) => ({ ...value, page: value.page - 1 }))}>Trang trước</Button><span className="text-sm">{pagination.page}/{pagination.totalPages}</span><Button size="sm" variant="secondary" disabled={pagination.page >= pagination.totalPages} onClick={() => setPagination((value) => ({ ...value, page: value.page + 1 }))}>Trang sau</Button></div></nav>}
    <BookingDialog booking={selected} canUpdate={canUpdate} onClose={() => setSelected(null)} onUpdated={async () => { setSelected(null); await load(); }} />
  </div>;
}
