import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import {PrismaClient} from '@prisma/client';
import {PrismaPg} from '@prisma/adapter-pg';
import pg from 'pg';
const env=JSON.parse(readFileSync('../report-output/full-system-qa/runtime.json','utf8'));
const f=JSON.parse(readFileSync('../report-output/full-system-qa/actors.json','utf8'));
assert.equal(f.database,new URL(env.DATABASE_URL).pathname.slice(1)); assert.match(f.database,/^beautybook_test_restriction_\d+$/);
const {scanControllers}=createRequire(import.meta.url)('./controller-metadata.cjs');
const routes=scanControllers(process.cwd()).routes, api='http://localhost:3012/api/v1', b=f.businesses[0], foreign=f.businesses[1];
const tokens={},results=[];let n=0;
const pool=new pg.Pool({connectionString:env.DATABASE_URL}),db=new PrismaClient({adapter:new PrismaPg(pool)});
function save(){const round=process.argv[2]||'baseline';const data=JSON.stringify({database:f.database,updatedAt:new Date().toISOString(),round,results},null,2);writeFileSync(`${env.QA_OUTPUT}/api-${round}.json`,data);writeFileSync(`${env.QA_OUTPUT}/api-results.json`,data);}
async function scenario(id,feature,fn){try{const detail=await fn();results.push({id,feature,status:'PASS',kind:'REAL_API_DATABASE',detail});}catch(e){results.push({id,feature,status:'FAIL',kind:'REAL_API_DATABASE',error:String(e.message).slice(0,1600)});console.log(`FAIL ${id}: ${String(e.message).slice(0,350)}`);}save();}
async function call(method,path,actor,data,headers={}){
 const response=await fetch(`${api}${path}`,{method,headers:{'Content-Type':'application/json','X-Forwarded-For':`127.8.${Math.floor(++n/200)%200}.${n%200+1}`,...(actor?{Authorization:`Bearer ${tokens[actor]}`}:{ }),...headers},...(data!==undefined?{body:JSON.stringify(data)}:{})});
 const text=await response.text();let body;try{body=JSON.parse(text);}catch{body=text;}
 return {status:response.status,body,headers:response.headers};
}
function status(r,expected){assert.ok((Array.isArray(expected)?expected:[expected]).includes(r.status),`HTTP ${r.status}, expected ${expected}: ${JSON.stringify(r.body).slice(0,500)}`);return r.body;}
async function login(key){const a=f.actors[key];const r=await call('POST','/auth/login',null,{email:a.email,password:a.password,workspace:a.workspace,refreshTokenTransport:'BODY'});status(r,200);tokens[key]=r.body.accessToken;return r.body;}
const shape=data=>Array.isArray(data)?{type:'array',count:data.length}:data&&typeof data==='object'?{keys:Object.keys(data)}:{type:typeof data};
try{
 for(const key of ['customer0','customer1','customer2','customer3','owner0','owner1','staff0','receptionist0','platform_admin'])await scenario(`AUTH-LOGIN-${key}`,'auth.login',async()=>{const data=await login(key);assert.ok(data.user.roles.includes(f.actors[key].role));return {role:f.actors[key].role,sessionType:data.user.sessionType};});
 await scenario('AUTH-INACTIVE','auth.inactive',async()=>{status(await call('POST','/auth/login',null,{email:f.actors.customer13.email,password:env.QA_PASSWORD}),[401,403]);return {denied:true};});
 // Every protected operation is exercised without identity. This is security
 // coverage ONLY, never a successful business-operation verdict.
 for(const [i,r] of routes.entries())if(!r.isPublic)await scenario(`BOUNDARY-${i+1}`,`${r.verb.toUpperCase()} ${r.path}`,async()=>{const p=r.path.replace(/\{[^}]+\}/g,()=>randomUUID());status(await call(r.verb.toUpperCase(),p,null,r.verb==='get'?undefined:{}),401);return {anonymousDenied:true};});
 const day=new Date(Date.now()+3*86400000).toISOString().slice(0,10),q=`branchId=${b.branchId}&businessId=${b.id}&serviceIds=${b.serviceId}&serviceId=${b.serviceId}&staffId=${b.staffId}&date=${day}&startDate=${day}&endDate=${new Date(Date.now()+10*86400000).toISOString().slice(0,10)}&from=${day}&to=${day}&year=${new Date().getFullYear()}`;
 const reads=[
 ['public','/health/ready'],['public','/platform-settings/public'],['public','/branches'],['public','/branches/locations/districts'],['public',`/branches/${b.branchId}`],['public',`/branches/${b.branchId}/services`],['public',`/branches/${b.branchId}/reviews`],['public','/services/search'],['public','/services/canonical'],['public','/services/categories'],['public','/services'],['public',`/services/${b.serviceId}`],['public',`/services/${b.serviceId}/variants`],['public','/staff/public'],['public',`/staff/public/${b.staffId}`],['public','/combos/public'],['public',`/reviews/business/${b.id}`],['public',`/reviews/public/staff/${b.staffId}`],['public',`/reviews/service/${b.serviceId}`],['public',`/promotions/service/${b.serviceId}`],
 ['customer0','/users/me/profile'],['customer0','/auth/sessions'],['customer0','/auth/security-history'],['customer0','/bookings/my-appointments'],['customer0','/bookings/self-booking-policy'],['customer0','/saved-services'],['customer0','/customer/saved-services'],['customer0','/vouchers/mine'],['customer0','/recurring/mine'],['customer0','/privacy/center'],['customer0','/privacy/data-requests'],['customer0','/privacy/marketing-preferences'],['customer0','/notifications'],['customer0','/notifications/unread-count'],['customer0','/payments'],['customer0','/payments/packages'],['customer0','/payments/package-purchases'],
 ['owner0','/business/onboarding/config'],['owner0','/business/onboarding/mine'],['owner0',`/business/${b.id}/members`],['owner0',`/business/${b.id}/cancellation-policy`],['owner0','/branches/accessible'],['owner0',`/branches/accessible/${b.branchId}`],['owner0',`/branches/${b.branchId}/preview`],['owner0','/services/manage'],['owner0','/services/workspace/manage'],['owner0','/services/categories/manage'],['owner0','/staff'],['owner0',`/staff/${b.staffId}`],['owner0',`/staff/${b.staffId}/services`],['owner0',`/staff/${b.staffId}/offboarding-impact`],['owner0',`/staff/${b.staffId}/commission`],['owner0','/staff/invitations'],['owner0','/combos'],['owner0',`/combos/${b.comboId}`],['owner0','/bookings'],['owner0','/bookings/salon-queue'],['owner0','/bookings/salon-violations'],['owner0','/bookings/scheduler'],['owner0','/bookings/stats'],['owner0',`/bookings/by-branch/${b.branchId}`],['owner0','/bookings/change-requests/pending'],['owner0','/reviews/manage'],['owner0',`/reviews/staff/${b.staffId}`],['owner0','/promotions'],['owner0','/vouchers'],['owner0','/operational-impacts'],['owner0','/ownership-transfers'],['owner0',`/ownership-transfers/business/${b.id}/versions`],['owner0','/payments/providers'],['owner0','/payments/policies'],['owner0','/payments/ledger'],['owner0','/payments/platform-statements'],
 ...['overview','owner-dashboard','revenue','financial-summary','categories','services','staff-performance'].map(x=>['owner0',`/reports/${x}`]),
 ...['settings','trust-snapshots','trust-actions','audit-logs','business-directory','branch-directory','compliance-queue','finance-overview','marketing-overview'].map(x=>['platform_admin',`/admin/${x}`]),['platform_admin',`/business/${b.id}/detail`],['platform_admin','/users'],['platform_admin',`/users/${f.actors.customer0.id}`],['platform_admin',`/users/${f.actors.customer0.id}/permissions`],['platform_admin','/services/admin-curated/all'],['platform_admin','/services/canonical/manage'],['platform_admin','/branches/manage'],['platform_admin','/ownership-transfers/platform/pending'],['platform_admin','/reports/top-salons'],['platform_admin','/reports/user-growth'],['staff0','/staff/me'],['staff0','/bookings/salon-queue'],['receptionist0','/bookings/scheduler'],
 ];
 for(const [actor,path]of reads)await scenario(`READ-${actor}-${path}`,path,async()=>{const query=/^\/branches\/[^/]+\/(services|reviews)$/.test(path)?'page=1&limit=20':q;const r=await call('GET',`${path}?${query}`,actor==='public'?null:actor);return {...shape(status(r,200)),role:actor};});
 await scenario('TENANT-OWNER-FOREIGN','tenant isolation',async()=>{status(await call('PATCH',`/services/${foreign.serviceId}`,'owner0',{price:1}),403);status(await call('GET',`/branches/${foreign.branchId}/preview`,'owner0'),403);status(await call('GET',`/bookings/by-branch/${foreign.branchId}`,'receptionist0'),403);assert.equal(Number((await db.branchServiceOffering.findUniqueOrThrow({where:{id:foreign.serviceId}})).price),200000);return {foreignUnchanged:true};});
 await scenario('PUBLIC-DRAFT','publication isolation',async()=>{const rows=status(await call('GET','/branches'),200);assert.ok(!JSON.stringify(rows).includes('Chi nhánh nháp'));const draft=await db.branch.findFirstOrThrow({where:{businessId:b.id,reviewStatus:'DRAFT'}});status(await call('GET',`/branches/${draft.id}`),404);return {draftHidden:true};});
 for(const path of ['/loyalty','/waitlist','/invoices','/operations/waitlist','/operations/invoices'])await scenario(`REMOVED-${path}`,'removed functionality',async()=>{status(await call('GET',path,'owner0'),404);return {routeUnavailable:true};});
 await scenario('PROFILE-PERSIST','profile',async()=>{status(await call('PATCH','/users/me/profile','customer0',{fullName:'Khách hàng QA đã cập nhật',address:'Địa chỉ kiểm thử'}),200);assert.equal((await db.user.findUniqueOrThrow({where:{id:f.actors.customer0.id}})).fullName,'Khách hàng QA đã cập nhật');const refreshed=await login('customer0');assert.equal(refreshed.user.fullName,'Khách hàng QA đã cập nhật');return {persistedAndFreshSession:true};});
 await scenario('PROFILE-PRIVILEGE-INJECTION','profile permissions',async()=>{status(await call('PATCH','/users/me/profile','customer0',{roles:['PLATFORM_ADMIN']}),400);return {massAssignmentDenied:true};});
 await scenario('SAVED-SERVICES','saved services',async()=>{for(let i=0;i<2;i++)status(await call('POST',`/saved-services/${b.serviceId}`,'customer0',{}),[200,201]);assert.equal(await db.customerSavedService.count({where:{customerId:f.actors.customer0.customerId,branchServiceOfferingId:b.serviceId}}),1);const other=status(await call('GET','/saved-services','customer1'),200);assert.ok(!JSON.stringify(other).includes(b.serviceId));status(await call('DELETE',`/saved-services/${b.serviceId}`,'customer0'),200);return {idempotentAndAccountIsolated:true};});
 let booking;
 await scenario('BOOKING-CREATE-RETRY','booking creation/idempotency',async()=>{const slots=status(await call('GET',`/bookings/available-slots?${q}`),200).slots;assert.ok(slots.length);const payload={branchId:b.branchId,serviceIds:[b.serviceId],staffId:b.staffId,appointmentDate:slots[0].start};const key=randomUUID();booking=status(await call('POST','/bookings','customer0',payload,{'Idempotency-Key':key}),201);const repeated=status(await call('POST','/bookings','customer0',payload,{'Idempotency-Key':key}),[200,201]);assert.equal(booking.id,repeated.id);assert.equal(booking.status,'PENDING');assert.equal(Number(booking.finalAmount),200000);assert.equal(await db.booking.count({where:{id:booking.id}}),1);return {bookingId:booking.id,status:booking.status,price:Number(booking.finalAmount)};});
 if(booking){
 await scenario('BOOKING-FRESH-SESSION','booking persistence/synchronization',async()=>{await login('customer0');const own=status(await call('GET',`/bookings/${booking.id}`,'customer0'),200),operator=status(await call('GET',`/bookings/${booking.id}`,'receptionist0'),200);assert.equal(own.id,operator.id);status(await call('GET',`/bookings/${booking.id}`,'customer1'),403);status(await call('GET',`/bookings/${booking.id}`,'owner1'),403);return {bookingId:booking.id,customerAndOperatorAgree:true};});
 await scenario('BOOKING-CONFIRM','booking lifecycle',async()=>{const data=status(await call('PATCH',`/bookings/${booking.id}/status`,'receptionist0',{status:'CONFIRMED'}),200);assert.equal(data.status,'CONFIRMED');return {confirmed:true};});
 await scenario('BOOKING-FORBIDDEN-TRANSITION','booking lifecycle',async()=>{status(await call('PATCH',`/bookings/${booking.id}/status`,'customer0',{status:'COMPLETED'}),[400,403]);assert.equal((await db.booking.findUniqueOrThrow({where:{id:booking.id}})).status,'CONFIRMED');return {customerCannotComplete:true};});
 await scenario('PAYMENT-CASH','sandbox payment bookkeeping',async()=>{const paid=status(await call('POST','/payments/collect','receptionist0',{bookingId:booking.id,method:'CASH',amount:200000,idempotencyKey:randomUUID()},{'Idempotency-Key':randomUUID()}),[200,201]);const context=status(await call('GET',`/payments/checkout/${booking.id}`,'owner0'),200);return {payment:shape(paid),checkout:shape(context),bookingId:booking.id};});
 await scenario('BOOKING-CANCEL','booking cancellation',async()=>{const data=status(await call('PATCH',`/bookings/${booking.id}/status`,'customer0',{status:'CANCELLED',note:'Kiểm thử hủy đúng hạn'}),200);assert.equal(data.status,'CANCELLED');return {bookingId:booking.id,status:data.status};});
 }
 await scenario('BOOKING-PAST','booking validation',async()=>{status(await call('POST','/bookings','customer1',{branchId:b.branchId,serviceIds:[b.serviceId],appointmentDate:'2020-01-01T02:00:00Z'},{'Idempotency-Key':randomUUID()}),[400,409]);return {pastDenied:true};});
 await scenario('NOTIFICATIONS','notifications',async()=>{status(await call('PATCH','/notifications/read-all','customer0',{}),200);const unread=status(await call('GET','/notifications/unread-count','customer0'),200);return {unread:unread.count??unread.unreadCount??unread};});
 // Actual source hashes are stored independently; no credentials/tokens in evidence.
 console.log(JSON.stringify({scenarios:results.length,pass:results.filter(x=>x.status==='PASS').length,fail:results.filter(x=>x.status==='FAIL').length}));
}finally{save();await db.$disconnect();await pool.end();}
