import { useCallback, useEffect, useMemo, useState } from 'react';
import { FileClock, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { adminApi } from '../../api/apiClient';
import { Badge, Button, Card, Dialog, EmptyState, ErrorState, Field, Input, MetricCard, Page, PageHeader, Select, Skeleton } from '../../components/ui';

const actionTone = { DELETE: 'danger', CANCEL: 'danger', FORCE_CANCEL: 'danger', REFUND: 'warning', STATUS_CHANGE: 'warning', UPDATE: 'info', CREATE: 'success', LOGIN: 'success', LOGOUT: 'neutral' };
const formatJson = (value) => value == null ? 'Không có dữ liệu' : JSON.stringify(value, null, 2);

export function AdminAudit({ scopeLabel = 'nền tảng' }) {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null);
  const [filters, setFilters] = useState({ search: '', action: 'ALL', entity: 'ALL' }); const [page, setPage] = useState(1); const pageSize = 20;
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await adminApi.getAuditLogs() || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const actions = useMemo(() => [...new Set(rows.map((row) => row.action).filter(Boolean))].sort(), [rows]);
  const entities = useMemo(() => [...new Set(rows.map((row) => row.entityType).filter(Boolean))].sort(), [rows]);
  const filtered = useMemo(() => { const term = filters.search.trim().toLocaleLowerCase('vi'); return rows.filter((row) => (filters.action === 'ALL' || row.action === filters.action) && (filters.entity === 'ALL' || row.entityType === filters.entity) && (!term || [row.entityType, row.entityId, row.reason, row.user?.fullName, row.user?.email].some((value) => String(value || '').toLocaleLowerCase('vi').includes(term)))); }, [filters, rows]);
  useEffect(() => { setPage(1); }, [filters]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const todayCount = rows.filter((row) => new Date(row.createdAt).toDateString() === new Date().toDateString()).length;
  return <Page>
    <PageHeader eyebrow="Quản trị dữ liệu" title="Nhật ký kiểm toán" description={`100 sự kiện gần nhất trong phạm vi ${scopeLabel} do hệ thống ghi nhận. Dữ liệu chỉ đọc, dùng để truy vết ai đã thay đổi gì và vào thời điểm nào.`} actions={<Button variant="secondary" onClick={load}><RefreshCw size={16} />Làm mới</Button>} />
    <div className="grid gap-3 sm:grid-cols-3"><MetricCard icon={FileClock} label="Sự kiện đã tải" value={rows.length} /><MetricCard icon={ShieldCheck} label="Phát sinh hôm nay" value={todayCount} tone="success" /><MetricCard icon={Search} label="Kết quả bộ lọc" value={filtered.length} tone="info" /></div>
    <Card className="grid gap-3 p-4 md:grid-cols-[minmax(15rem,1fr)_14rem_14rem]"><Field label="Tìm kiếm"><Input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Người thao tác, lý do hoặc mã đối tượng" /></Field><Field label="Hành động"><Select value={filters.action} onChange={(event) => setFilters({ ...filters, action: event.target.value })}><option value="ALL">Tất cả hành động</option>{actions.map((action) => <option key={action} value={action}>{action}</option>)}</Select></Field><Field label="Loại đối tượng"><Select value={filters.entity} onChange={(event) => setFilters({ ...filters, entity: event.target.value })}><option value="ALL">Tất cả đối tượng</option>{entities.map((entity) => <option key={entity} value={entity}>{entity}</option>)}</Select></Field></Card>
    {loading ? <Card className="p-5"><Skeleton rows={8} /></Card> : error ? <Card><ErrorState message={error} onRetry={load} /></Card> : !visible.length ? <Card><EmptyState icon={FileClock} title="Không có sự kiện phù hợp" description="Thử đổi bộ lọc tìm kiếm." /></Card> : <Card className="overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[920px] text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-xs text-[var(--bb-muted)]"><tr><th className="p-3 text-left">Thời gian</th><th className="p-3 text-left">Người thao tác</th><th className="p-3">Hành động</th><th className="p-3 text-left">Đối tượng</th><th className="p-3 text-left">Lý do</th><th className="p-3">Chi tiết</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id} className="border-t border-[var(--bb-border)]"><td className="whitespace-nowrap p-3">{new Date(row.createdAt).toLocaleString('vi-VN')}</td><td className="p-3"><strong>{row.user?.fullName || 'Hệ thống'}</strong><p className="text-xs text-[var(--bb-muted)]">{row.user?.email || 'Tác vụ tự động'}</p></td><td className="p-3 text-center"><Badge tone={actionTone[row.action] || 'neutral'}>{row.action}</Badge></td><td className="p-3"><strong>{row.entityType}</strong><p className="max-w-48 truncate font-mono text-xs text-[var(--bb-muted)]">{row.entityId || '—'}</p></td><td className="max-w-sm truncate p-3 text-[var(--bb-muted)]">{row.reason || '—'}</td><td className="p-3 text-center"><Button size="sm" variant="ghost" onClick={() => setSelected(row)}>Mở</Button></td></tr>)}</tbody></table></div><div className="divide-y divide-[var(--bb-border)] md:hidden">{visible.map((row) => <button key={row.id} onClick={() => setSelected(row)} className="block min-h-11 w-full p-4 text-left hover:bg-[var(--bb-surface-subtle)]"><div className="flex items-center justify-between gap-2"><strong>{row.entityType}</strong><Badge tone={actionTone[row.action] || 'neutral'}>{row.action}</Badge></div><p className="mt-2 text-sm">{row.user?.fullName || 'Hệ thống'} · {new Date(row.createdAt).toLocaleString('vi-VN')}</p><p className="mt-1 truncate text-xs text-[var(--bb-muted)]">{row.reason || row.entityId || 'Không có ghi chú'}</p></button>)}</div><footer className="flex items-center justify-between border-t border-[var(--bb-border)] p-4 text-sm"><span>Trang {page}/{pageCount}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Trước</Button><Button size="sm" variant="secondary" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)}>Sau</Button></div></footer></Card>}
    <Dialog open={Boolean(selected)} onClose={() => setSelected(null)} title="Chi tiết sự kiện kiểm toán" description={selected ? `${selected.entityType} · ${selected.entityId || 'không có mã'}` : ''} size="lg"><div className="space-y-5 text-sm"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-[var(--bb-muted)]">Người thao tác</dt><dd className="font-semibold">{selected?.user?.fullName || 'Hệ thống'} · {selected?.user?.email || 'tác vụ tự động'}</dd></div><div><dt className="text-[var(--bb-muted)]">Thời gian</dt><dd className="font-semibold">{selected?.createdAt ? new Date(selected.createdAt).toLocaleString('vi-VN') : '—'}</dd></div><div><dt className="text-[var(--bb-muted)]">Hành động</dt><dd><Badge tone={actionTone[selected?.action] || 'neutral'}>{selected?.action}</Badge></dd></div><div><dt className="text-[var(--bb-muted)]">Lý do</dt><dd className="font-semibold">{selected?.reason || 'Không ghi nhận'}</dd></div></dl><div className="grid gap-4 lg:grid-cols-2"><section><h3 className="font-bold">Dữ liệu trước</h3><pre className="mt-2 max-h-80 overflow-auto rounded-lg bg-zinc-950 p-4 text-xs leading-5 text-zinc-100">{formatJson(selected?.oldData)}</pre></section><section><h3 className="font-bold">Dữ liệu sau</h3><pre className="mt-2 max-h-80 overflow-auto rounded-lg bg-zinc-950 p-4 text-xs leading-5 text-zinc-100">{formatJson(selected?.newData)}</pre></section></div></div></Dialog>
  </Page>;
}

export default AdminAudit;
