import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Ban, CheckCircle2, RefreshCw, ShieldAlert } from 'lucide-react';
import toast from 'react-hot-toast';
import { adminApi } from '../../api/apiClient';
import { useAuthStore } from '../../store/authStore';
import { Badge, Button, Card, Dialog, EmptyState, ErrorState, Field, MetricCard, Page, PageHeader, Select, Skeleton, Textarea } from '../../components/ui';

const pct = (value) => `${(Number(value || 0) * 100).toFixed(1)}%`;
const alertTone = { DANGER: 'danger', WARN: 'warning', OK: 'success' };
const actions = [
  ['WARNING_SENT', 'Gửi cảnh báo'], ['EXPLANATION_REQUESTED', 'Yêu cầu giải trình'], ['MONITORING_STARTED', 'Đưa vào theo dõi'],
  ['BOOKING_RESTRICTED', 'Tạm hạn chế nhận booking'], ['SUSPENDED', 'Tạm ngưng'], ['RESTORED', 'Khôi phục'], ['NOTE_ADDED', 'Ghi chú xử lý'],
];

export function AdminViolations() {
  const can = useAuthStore((state) => state.can); const canManage = can('admin:trust_snapshot:manage');
  const [summary, setSummary] = useState({ data: [] }); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [modal, setModal] = useState(null); const [action, setAction] = useState('WARNING_SENT'); const [targetBranchId, setTargetBranchId] = useState(''); const [reason, setReason] = useState(''); const [internalNote, setInternalNote] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [snapshots, actionRows] = await Promise.all([adminApi.getTrustSnapshots(), adminApi.getTrustActions()]); setSummary(snapshots || { data: [] }); setHistory(Array.isArray(actionRows) ? actionRows : []); } catch (e) { setError(e.message || 'Không thể tải Trust & Safety.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const rebuild = async () => { setBusy(true); try { setSummary(await adminApi.rebuildTrustSnapshots()); toast.success('Đã cập nhật trust snapshot'); } catch (e) { toast.error(e.message); } finally { setBusy(false); } };
  const open = (item) => { setModal(item); setAction(item.alertLevel === 'DANGER' ? 'EXPLANATION_REQUESTED' : 'WARNING_SENT'); setTargetBranchId(''); setReason(''); setInternalNote(''); };
  const submit = async () => { if (!reason.trim()) return toast.error('Nhập lý do xử lý'); setBusy(true); try { await adminApi.createTrustAction({ businessId: modal.businessId, branchId: targetBranchId || undefined, action, reason: reason.trim(), internalNote: internalNote.trim() || undefined }); toast.success('Đã ghi nhận hành động Trust & Safety'); setModal(null); await load(); } catch (e) { toast.error(e.message); } finally { setBusy(false); } };
  const snapshots = summary.data || [];
  return <Page>
    <PageHeader eyebrow="Trust & Safety" title="Tín hiệu cần theo dõi" description={`Trust score dùng dữ liệu ${summary.periodDays || 90} ngày; customer no-show chỉ được theo dõi và không trực tiếp phạt cơ sở.`} actions={canManage ? <Button onClick={rebuild} loading={busy}><RefreshCw size={16} />Tạo snapshot ngay</Button> : null} />
    <div className="grid gap-3 sm:grid-cols-4"><MetricCard icon={Ban} label="DANGER" value={summary.dangerCount || 0} /><MetricCard icon={AlertTriangle} label="WARN" value={summary.warningCount || 0} tone="warning" /><MetricCard icon={CheckCircle2} label="Đang theo dõi" value={summary.monitoredCount || 0} tone="success" /><MetricCard icon={ShieldAlert} label="Doanh nghiệp đã tính" value={summary.totalBusinesses || 0} /></div>
    <Card className="p-4"><p className="text-sm text-[var(--bb-muted)]">Cập nhật lần cuối: <strong className="text-[var(--bb-ink)]">{summary.lastComputedAt ? new Date(summary.lastComputedAt).toLocaleString('vi-VN') : 'Chưa có snapshot'}</strong></p></Card>
    {loading ? <Card className="p-5"><Skeleton rows={8} /></Card> : error ? <Card><ErrorState message={error} onRetry={load} /></Card> : snapshots.length === 0 ? <Card><EmptyState icon={ShieldAlert} title="Chưa có trust snapshot" description="Bấm “Tạo snapshot ngay” để tổng hợp dữ liệu hiện tại." /></Card> : <Card className="overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-sm"><thead className="bg-[var(--bb-surface-subtle)] text-xs text-[var(--bb-muted)]"><tr><th className="p-3 text-left">Doanh nghiệp / lý do</th><th className="p-3 text-right">Tổng lịch</th><th className="p-3 text-right">Cơ sở hủy</th><th className="p-3 text-right">Hủy trễ</th><th className="p-3 text-right">Xác nhận TB</th><th className="p-3 text-right">Trust</th><th className="p-3">Mức</th><th className="p-3">Xử lý</th></tr></thead><tbody>{snapshots.map((item) => <tr key={item.id} className="border-t border-[var(--bb-border)] align-top"><td className="p-3"><strong>{item.business?.name}</strong>{item.reasons?.length ? <ul className="mt-2 list-disc pl-4 text-xs text-[var(--bb-muted)]">{item.reasons.map((text) => <li key={text}>{text}</li>)}</ul> : <p className="mt-1 text-xs text-[var(--bb-muted)]">Chưa có tín hiệu bất thường.</p>}</td><td className="p-3 text-right">{item.totalBookings}</td><td className="p-3 text-right">{pct(item.cancellationRate)}</td><td className="p-3 text-right">{pct(item.lateCancelBySalonRate)}</td><td className="p-3 text-right">{Math.round(item.avgConfirmationTimeMinutes || 0)} phút</td><td className="p-3 text-right font-bold">{Math.round(item.trustScore)}</td><td className="p-3 text-center"><Badge tone={alertTone[item.alertLevel]}>{item.alertLevel}</Badge></td><td className="p-3">{canManage && <Button size="sm" variant="secondary" onClick={() => open(item)}>Xử lý</Button>}</td></tr>)}</tbody></table></div><div className="divide-y divide-[var(--bb-border)] md:hidden">{snapshots.map((item) => <article key={item.id} className="p-4"><div className="flex justify-between gap-2"><strong>{item.business?.name}</strong><Badge tone={alertTone[item.alertLevel]}>{item.alertLevel}</Badge></div><p className="mt-2 text-sm">Trust {Math.round(item.trustScore)} · {item.totalBookings} lịch</p>{item.reasons?.map((text) => <p key={text} className="mt-1 text-xs text-[var(--bb-muted)]">• {text}</p>)}{canManage && <Button className="mt-3" size="sm" variant="secondary" onClick={() => open(item)}>Xử lý</Button>}</article>)}</div></Card>}
    <Card className="overflow-hidden"><div className="border-b border-[var(--bb-border)] p-5"><h2 className="font-bold">Lịch sử xử lý</h2></div>{history.length ? <ul className="divide-y divide-[var(--bb-border)]">{history.slice(0, 30).map((row) => <li key={row.id} className="p-4 text-sm"><div className="flex flex-wrap items-center gap-2"><Badge tone={row.action === 'SUSPENDED' ? 'danger' : 'warning'}>{row.action}</Badge><strong>{row.business?.name}{row.branch?.name ? ` · ${row.branch.name}` : ''}</strong><span className="text-[var(--bb-muted)]">{new Date(row.createdAt).toLocaleString('vi-VN')}</span></div><p className="mt-2">{row.reason}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{row.actor?.fullName || row.actor?.email} · {row.statusBefore || '—'} → {row.statusAfter || '—'}</p></li>)}</ul> : <EmptyState title="Chưa có hành động xử lý" />}</Card>
    <Dialog open={Boolean(modal)} onClose={() => setModal(null)} title="Xử lý Trust & Safety" description={modal?.business?.name} footer={<><Button variant="secondary" onClick={() => setModal(null)}>Hủy</Button><Button loading={busy} onClick={submit}>Xác nhận</Button></>}><div className="space-y-4"><Field label="Phạm vi xử lý"><Select value={targetBranchId} onChange={(e) => setTargetBranchId(e.target.value)}><option value="">Toàn doanh nghiệp</option>{modal?.business?.branches?.map((branch) => <option key={branch.id} value={branch.id}>Chi nhánh: {branch.name} ({branch.status})</option>)}</Select></Field><Field label="Hành động"><Select value={action} onChange={(e) => setAction(e.target.value)}>{actions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Lý do" required><Textarea value={reason} onChange={(e) => setReason(e.target.value)} /></Field><Field label="Ghi chú nội bộ"><Textarea value={internalNote} onChange={(e) => setInternalNote(e.target.value)} /></Field></div></Dialog>
  </Page>;
}

export default AdminViolations;
