import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import toast from 'react-hot-toast';
import { Clock3, ShieldCheck, TicketPercent, UserRound } from 'lucide-react';
import { bookingsApi, recurringApi, servicesApi } from '../../api/apiClient';
import { useBookingStore } from '../../store/bookingStore';
import { useAuthStore } from '../../store/authStore';
import { Button, Card, InlineNotice, Skeleton } from '../../components/ui';
import { BookingLayout } from '../../components/customer/BookingLayout';

export default function BookingConfirm() {
  const navigate = useNavigate(); const state = useBookingStore(); const user = useAuthStore((s) => s.user); const [services, setServices] = useState([]); const [preview, setPreview] = useState(null); const [recurringPreview, setRecurringPreview] = useState(null); const [previewingRecurring, setPreviewingRecurring] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (!state.branchId || !state.serviceIds.length || !state.slot) { navigate('/book', { replace: true }); return; } servicesApi.getAll(state.branchId).then((result) => { const list = result.data ?? result ?? []; setServices(list.filter((item) => state.serviceIds.includes(item.id))); }).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [state.branchId, state.serviceIds, state.slot, navigate]);
  useEffect(() => { if (!services.length) return; const subtotal = state.combo ? Number(state.combo.comboPrice) : services.reduce((sum, item) => sum + Number(item.price || 0), 0); bookingsApi.previewPrice({ branchId: state.branchId, serviceIds: state.serviceIds, comboId: state.comboId, voucherCode: state.voucherCode || undefined }).then(setPreview).catch(() => setPreview({ subtotal, voucherDiscount: 0, finalAmount: subtotal, voucherApplied: false })); }, [services, state.branchId, state.serviceIds, state.comboId, state.voucherCode]);
  const recurringPayload = () => ({ branchId: state.branchId, serviceIds: state.serviceIds, comboId: state.comboId || undefined, staffId: state.staffId || undefined, staffMode: state.recurring.staffMode, frequency: state.recurring.frequency, startDate: state.date, preferredTime: format(new Date(state.slot.start), 'HH:mm'), occurrenceCount: state.recurring.occurrenceCount });
  useEffect(() => { if (!user || !state.recurring.enabled || !state.slot) { setRecurringPreview(null); return; } setPreviewingRecurring(true); recurringApi.preview(recurringPayload()).then(setRecurringPreview).catch((error) => toast.error(error.message)).finally(() => setPreviewingRecurring(false)); }, [user, state.recurring.enabled, state.recurring.frequency, state.recurring.occurrenceCount, state.recurring.staffMode, state.slot?.start, state.staffId, state.comboId]);
  const confirm = async () => { if (submitting) return; setSubmitting(true); try { let booking; let plan; if (state.recurring.enabled) { plan = await recurringApi.create({ ...recurringPayload(), skipConflicts: state.recurring.skipConflicts, note: state.customerInfo.note }); booking = plan.bookings?.[0]; } else { booking = await bookingsApi.create({ branchId: state.branchId, serviceIds: state.serviceIds, comboId: state.comboId || undefined, appointmentDate: state.slot.start, note: state.customerInfo.note, staffId: state.staffId, voucherCode: state.voucherCode || undefined, source: 'ONLINE_WEB' }); } toast.success(plan ? `Đã tạo chuỗi ${plan.bookings?.length || 0} lịch hẹn` : booking.status === 'PENDING' ? 'Đã gửi yêu cầu đặt lịch' : 'Đặt lịch thành công'); state.reset(); navigate('/book/success', { state: { booking, plan } }); } catch (err) { if (err.status === 409 || /trùng|conflict|already|khung giờ/i.test(err.message)) { toast.error('Một hoặc nhiều khung giờ vừa có người đặt. Vui lòng kiểm tra lại.'); navigate('/book/time'); } else toast.error(err.message || 'Đặt lịch thất bại'); } finally { setSubmitting(false); } };
  const subtotal = state.combo ? Number(state.combo.comboPrice) : services.reduce((sum, item) => sum + Number(item.price || 0), 0); const duration = state.combo?.durationMinutes || services.reduce((sum, item) => sum + Number(item.durationMinutes || 0), 0); const total = preview?.finalAmount ?? subtotal;
  const summary = <Card className="sticky top-24 p-5"><h2 className="text-sm font-bold">Tóm tắt thanh toán</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-[var(--bb-muted)]">Tạm tính mỗi kỳ</span><span>{(preview?.subtotal ?? subtotal).toLocaleString('vi-VN')}₫</span></div>{preview?.voucherApplied && <div className="flex justify-between text-[var(--bb-success)]"><span>Voucher {preview.code}</span><span>-{Number(preview.voucherDiscount || 0).toLocaleString('vi-VN')}₫</span></div>}<div className="flex justify-between border-t border-[var(--bb-border)] pt-3 text-base font-bold"><span>{state.recurring.enabled ? 'Mỗi kỳ' : 'Tổng cộng'}</span><span className="text-[var(--bb-brand-strong)]">{total.toLocaleString('vi-VN')}₫</span></div></div><Button loading={submitting || previewingRecurring} disabled={loading || !preview || (state.recurring.enabled && !recurringPreview)} onClick={confirm} className="mt-5 w-full">{state.recurring.enabled ? 'Xác nhận chuỗi lịch' : 'Xác nhận đặt lịch'}</Button><p className="mt-3 text-center text-[11px] leading-5 text-[var(--bb-muted)]">Giá và khung giờ sẽ được hệ thống kiểm tra lại khi xác nhận.</p></Card>;
  return <BookingLayout step={5} title="Kiểm tra và xác nhận" description="Vui lòng đối chiếu dịch vụ, thời gian và thông tin liên hệ trước khi tạo lịch." aside={summary}>{loading ? <Skeleton rows={6} /> : <div className="space-y-6"><section><h2 className="text-sm font-bold">{state.combo ? `Combo ${state.combo.name}` : 'Dịch vụ đã chọn'}</h2><div className="mt-3 divide-y divide-[var(--bb-border)] rounded-xl border border-[var(--bb-border)]">{services.map((item) => <div key={item.id} className="flex items-start justify-between gap-4 p-4"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{item.durationMinutes || 0} phút</p></div>{!state.combo && <p className="font-bold">{Number(item.price || 0).toLocaleString('vi-VN')}₫</p>}</div>)}</div></section><div className="grid gap-3 sm:grid-cols-2"><Card className="p-4"><Clock3 size={18} className="text-[var(--bb-brand-strong)]" /><p className="mt-3 text-xs font-semibold text-[var(--bb-muted)]">Thời gian</p><p className="mt-1 text-sm font-bold">{state.slot && format(new Date(state.slot.start), 'dd/MM/yyyy · HH:mm')}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">Tổng thời lượng {duration} phút</p></Card><Card className="p-4"><UserRound size={18} className="text-[var(--bb-brand-strong)]" /><p className="mt-3 text-xs font-semibold text-[var(--bb-muted)]">Người đặt</p><p className="mt-1 text-sm font-bold">{state.customerInfo.fullName}</p><p className="mt-1 text-xs text-[var(--bb-muted)]">{state.customerInfo.phone}</p></Card></div>{state.recurring.enabled && <InlineNotice tone={recurringPreview?.conflictCount ? 'warning' : 'success'}>{previewingRecurring ? 'Đang kiểm tra toàn bộ chuỗi lịch…' : recurringPreview ? `${recurringPreview.availableCount} kỳ còn chỗ${recurringPreview.conflictCount ? `, ${recurringPreview.conflictCount} kỳ xung đột sẽ ${state.recurring.skipConflicts ? 'được bỏ qua' : 'cần xử lý'}.` : '.'}` : 'Chưa có kết quả kiểm tra chuỗi lịch.'}</InlineNotice>}{state.voucherCode && !state.recurring.enabled && <InlineNotice tone="success"><span className="flex items-center gap-2"><TicketPercent size={16} />Đã kiểm tra mã {state.voucherCode}{preview?.voucherApplied ? ' và áp dụng thành công.' : '; mã không tạo giảm giá trong kết quả hiện tại.'}</span></InlineNotice>}<InlineNotice tone="info"><span className="flex items-start gap-2"><ShieldCheck size={16} className="mt-0.5 shrink-0" />Hệ thống chống đặt trùng sẽ kiểm tra lại khung giờ trong transaction khi tạo lịch.</span></InlineNotice><div className="border-t border-[var(--bb-border)] pt-5"><Button variant="secondary" disabled={submitting} onClick={() => navigate('/book/info')}>Quay lại chỉnh sửa</Button></div></div>}</BookingLayout>;
}
