import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Star, UserRound, UsersRound } from 'lucide-react';
import { staffApi } from '../../api/apiClient';
import { useBookingStore } from '../../store/bookingStore';
import { Button, EmptyState, InlineNotice, Skeleton } from '../../components/ui';
import { BookingLayout, SelectionCard } from '../../components/customer/BookingLayout';

export default function BookingStep2() {
  const navigate = useNavigate(); const { branchId, serviceIds, staffId, setStaff } = useBookingStore(); const [staff, setStaffList] = useState([]); const [loading, setLoading] = useState(true); const [warning, setWarning] = useState('');
  useEffect(() => { if (!branchId || !serviceIds.length) { navigate('/book', { replace: true }); return; } setLoading(true); setWarning(''); staffApi.getPublic(branchId, serviceIds).then((data) => setStaffList(Array.isArray(data) ? data : [])).catch((e) => setWarning(`Không tải được danh sách chuyên viên: ${e.message}. Bạn vẫn có thể để hệ thống tự phân công.`)).finally(() => setLoading(false)); }, [branchId, serviceIds, navigate]);
  return <BookingLayout step={2} title="Chọn chuyên viên" description="Bạn có thể chọn một người cụ thể hoặc để BeautyBook tự tìm chuyên viên đủ kỹ năng và còn lịch phù hợp.">{warning && <InlineNotice tone="warning">{warning}</InlineNotice>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><SelectionCard selected={staffId === null} onClick={() => setStaff(null)} icon={<UsersRound size={18} />} title="Bất kỳ chuyên viên phù hợp" meta="Đề xuất · Hệ thống chỉ phân công người đã bật nhận lịch, phụ trách đủ dịch vụ và còn thời gian trống." trailing="Nên chọn" />{loading ? <div className="sm:col-span-2"><Skeleton rows={4} /></div> : staff.map((person) => { const specialty = person.specialties?.join(' · '); const rating = person.ratingCount ? <span className="inline-flex items-center gap-1"><Star size={13} fill="currentColor" />{person.rating} ({person.ratingCount})</span> : null; return <SelectionCard key={person.id} selected={staffId === person.id} onClick={() => setStaff(person.id)} icon={person.avatarUrl ? <img className="h-10 w-10 rounded-lg object-cover" src={person.avatarUrl} alt="" /> : <UserRound size={18} />} title={person.fullName || 'Chuyên viên'} meta={<>{person.professionalTitle || 'Chuyên viên làm đẹp'}{specialty ? <span className="block">{specialty}</span> : null}</>} trailing={rating} />; })}</div>{!loading && !staff.length && !warning && <EmptyState title="Chưa có chuyên viên phù hợp để chọn" description="Bạn vẫn có thể tiếp tục với lựa chọn tự phân công; hệ thống sẽ kiểm tra lại lịch và kỹ năng trước khi giữ chỗ." />}<div className="mt-6 flex justify-between border-t border-[var(--bb-border)] pt-5"><Button variant="secondary" onClick={() => navigate('/book')}>Quay lại</Button><Button onClick={() => navigate('/book/time')}>Tiếp tục</Button></div></BookingLayout>;
}
