import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Gift, MapPin, Scissors } from 'lucide-react';
import { branchesApi, combosApi, servicesApi } from '../../api/apiClient';
import { useBookingStore } from '../../store/bookingStore';
import { Button, EmptyState, ErrorState, Skeleton } from '../../components/ui';
import { BookingLayout, SelectionCard } from '../../components/customer/BookingLayout';

export default function BookingStep1() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const requestedBranch = params.get('branchId'); const requestedService = params.get('serviceId'); const requestedStaff = params.get('staffId'); const { branchId, serviceIds, comboId, setBranch, toggleService, setCombo, setStaff } = useBookingStore(); const [branches, setBranches] = useState([]); const [services, setServices] = useState([]); const [combos, setCombos] = useState([]); const [loading, setLoading] = useState(true); const [serviceLoading, setServiceLoading] = useState(false); const [error, setError] = useState('');
  const loadBranches = async () => { setLoading(true); setError(''); try { const result = await branchesApi.getAll(); setBranches(result.data ?? result); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { loadBranches(); }, []);
  useEffect(() => { if (requestedBranch && requestedBranch !== branchId && branches.some((branch) => branch.id === requestedBranch)) setBranch(requestedBranch); }, [requestedBranch, branchId, branches, setBranch]);
  useEffect(() => { if (requestedService && services.some((service) => service.id === requestedService) && !serviceIds.includes(requestedService)) toggleService(requestedService); }, [requestedService, services]);
  useEffect(() => { if (requestedStaff) setStaff(requestedStaff); }, [requestedStaff, setStaff]);
  useEffect(() => { if (!branchId) { setServices([]); setCombos([]); return; } setServiceLoading(true); Promise.all([servicesApi.getAll(branchId), combosApi.getPublic(branchId)]).then(([serviceResult, comboResult]) => { setServices(serviceResult.data ?? serviceResult); setCombos(comboResult.data ?? comboResult); }).catch((e) => setError(e.message)).finally(() => setServiceLoading(false)); }, [branchId]);
  return <BookingLayout step={1} title="Chọn chi nhánh và dịch vụ" description="Chọn dịch vụ riêng lẻ hoặc một combo trọn gói trong cùng chi nhánh.">{loading ? <Skeleton rows={5} /> : error && !branches.length ? <ErrorState message={error} onRetry={loadBranches} /> : <div className="space-y-7"><section><h2 className="mb-3 text-sm font-bold">1. Chi nhánh</h2><div className="grid gap-3 sm:grid-cols-2">{branches.map((branch) => <SelectionCard key={branch.id} selected={branchId === branch.id} onClick={() => setBranch(branch.id)} icon={<MapPin size={18} />} title={branch.branch_name || branch.name} meta={[branch.address, branch.district].filter(Boolean).join(', ') || 'Chưa cập nhật địa chỉ'} />)}</div></section>{branchId && !serviceLoading && combos.length > 0 && <section><h2 className="mb-3 text-sm font-bold">2. Combo ưu đãi <span className="font-normal text-[var(--bb-muted)]">(chọn một)</span></h2><div className="grid gap-3 sm:grid-cols-2">{combos.map((combo) => <SelectionCard key={combo.id} selected={comboId === combo.id} onClick={() => setCombo(comboId === combo.id ? null : combo)} icon={<Gift size={18} />} title={combo.name} meta={`${combo.durationMinutes || 0} phút · tiết kiệm ${Number(combo.savingAmount || 0).toLocaleString('vi-VN')}₫`} trailing={`${Number(combo.comboPrice || 0).toLocaleString('vi-VN')}₫`} />)}</div></section>}<section><h2 className="mb-3 text-sm font-bold">{combos.length ? 'Hoặc chọn dịch vụ riêng lẻ' : '2. Dịch vụ'} <span className="font-normal text-[var(--bb-muted)]">(có thể chọn nhiều)</span></h2>{!branchId ? <EmptyState title="Hãy chọn chi nhánh" description="Dịch vụ sẽ được tải theo chi nhánh bạn chọn." /> : serviceLoading ? <Skeleton rows={4} /> : !services.length ? <EmptyState title="Chưa có dịch vụ khả dụng" description="Chi nhánh này chưa trả về dịch vụ để đặt lịch." /> : <div className="grid gap-3 sm:grid-cols-2">{services.map((service) => <SelectionCard key={service.id} selected={!comboId && serviceIds.includes(service.id)} onClick={() => toggleService(service.id)} icon={<Scissors size={18} />} title={service.name} meta={`${service.durationMinutes || 0} phút`} trailing={`${Number(service.price || 0).toLocaleString('vi-VN')}₫`} />)}</div>}</section><div className="flex justify-end border-t border-[var(--bb-border)] pt-5"><Button disabled={!branchId || !serviceIds.length} onClick={() => navigate('/book/staff')}>Tiếp tục</Button></div></div>}</BookingLayout>;
}
