-- Additive integrity hardening. Read docs/DATABASE_MIGRATIONS.md before deployment.
-- No repair/delete/backfill is performed. Abort atomically on existing orphans.
BEGIN;
SET LOCAL lock_timeout = '10s';
ALTER TABLE "branch_state_transitions" ADD CONSTRAINT "branch_state_transitions_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "branch_state_transitions" ADD CONSTRAINT "branch_state_transitions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "price_adjustments" ADD CONSTRAINT "price_adjustments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "price_adjustments" ADD CONSTRAINT "price_adjustments_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "price_adjustments" ADD CONSTRAINT "price_adjustments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "promotion_redemptions" ADD CONSTRAINT "promotion_redemptions_promotion_id_fkey" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "promotion_redemptions" ADD CONSTRAINT "promotion_redemptions_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "promotion_redemptions" ADD CONSTRAINT "promotion_redemptions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "promotion_redemptions" ADD CONSTRAINT "promotion_redemptions_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_voucher_id_fkey" FOREIGN KEY ("voucher_id") REFERENCES "vouchers"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_customer_voucher_id_fkey" FOREIGN KEY ("customer_voucher_id") REFERENCES "customer_vouchers"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "service_variants" ADD CONSTRAINT "service_variants_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "service_price_rules" ADD CONSTRAINT "service_price_rules_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "service_price_rules" ADD CONSTRAINT "service_price_rules_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "service_variants"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "service_dependencies" ADD CONSTRAINT "service_dependencies_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "service_dependencies" ADD CONSTRAINT "service_dependencies_required_service_id_fkey" FOREIGN KEY ("required_service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "booking_service_adjustments" ADD CONSTRAINT "booking_service_adjustments_booking_service_id_fkey" FOREIGN KEY ("booking_service_id") REFERENCES "booking_services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "booking_service_adjustments" ADD CONSTRAINT "booking_service_adjustments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "booking_service_adjustments" ADD CONSTRAINT "booking_service_adjustments_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_cases" ADD CONSTRAINT "operational_impact_cases_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_cases" ADD CONSTRAINT "operational_impact_cases_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_cases" ADD CONSTRAINT "operational_impact_cases_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_cases" ADD CONSTRAINT "operational_impact_cases_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_items" ADD CONSTRAINT "operational_impact_items_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "operational_impact_cases"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_items" ADD CONSTRAINT "operational_impact_items_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_items" ADD CONSTRAINT "operational_impact_items_replacement_staff_id_fkey" FOREIGN KEY ("replacement_staff_id") REFERENCES "staff_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_items" ADD CONSTRAINT "operational_impact_items_replacement_branch_id_fkey" FOREIGN KEY ("replacement_branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "operational_impact_items" ADD CONSTRAINT "operational_impact_items_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "staff_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "waitlist_entries" ADD CONSTRAINT "waitlist_entries_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "review_moderation_events" ADD CONSTRAINT "review_moderation_events_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "review_moderation_events" ADD CONSTRAINT "review_moderation_events_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "review_appeals" ADD CONSTRAINT "review_appeals_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "review_appeals" ADD CONSTRAINT "review_appeals_appellant_id_fkey" FOREIGN KEY ("appellant_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "review_appeals" ADD CONSTRAINT "review_appeals_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_rules" ADD CONSTRAINT "loyalty_rules_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_rules" ADD CONSTRAINT "loyalty_rules_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_rules" ADD CONSTRAINT "loyalty_rules_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "loyalty_accounts_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "loyalty_accounts_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "loyalty_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_refund_request_id_fkey" FOREIGN KEY ("refund_request_id") REFERENCES "refund_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_reversal_of_id_fkey" FOREIGN KEY ("reversal_of_id") REFERENCES "loyalty_transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_booking_service_id_fkey" FOREIGN KEY ("booking_service_id") REFERENCES "booking_services"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoice_events" ADD CONSTRAINT "invoice_events_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "invoice_events" ADD CONSTRAINT "invoice_events_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_old_owner_id_fkey" FOREIGN KEY ("old_owner_id") REFERENCES "business_owner_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_new_owner_user_id_fkey" FOREIGN KEY ("new_owner_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_legal_entity_version_id_fkey" FOREIGN KEY ("legal_entity_version_id") REFERENCES "legal_entity_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_payout_account_version_id_fkey" FOREIGN KEY ("payout_account_version_id") REFERENCES "payout_account_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_requested_by_fkey" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_transfers" ADD CONSTRAINT "ownership_transfers_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_history" ADD CONSTRAINT "ownership_history_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_history" ADD CONSTRAINT "ownership_history_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "business_owner_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "ownership_history" ADD CONSTRAINT "ownership_history_transfer_id_fkey" FOREIGN KEY ("transfer_id") REFERENCES "ownership_transfers"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "legal_entity_versions" ADD CONSTRAINT "legal_entity_versions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "legal_entity_versions" ADD CONSTRAINT "legal_entity_versions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "payout_account_versions" ADD CONSTRAINT "payout_account_versions_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "payout_account_versions" ADD CONSTRAINT "payout_account_versions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "customer_business_segments" ADD CONSTRAINT "customer_business_segments_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "customer_business_segments" ADD CONSTRAINT "customer_business_segments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "customer_business_segments" ADD CONSTRAINT "customer_business_segments_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "customer_profiles" DROP CONSTRAINT "customer_profiles_user_id_fkey";
ALTER TABLE "customer_profiles" ADD CONSTRAINT "customer_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "business_owner_profiles" DROP CONSTRAINT "business_owner_profiles_user_id_fkey";
ALTER TABLE "business_owner_profiles" ADD CONSTRAINT "business_owner_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE NOT VALID;
ALTER TABLE "payments" ADD CONSTRAINT "payments_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "refund_requests" ADD CONSTRAINT "refund_requests_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "payment_transactions" ADD CONSTRAINT "payment_transactions_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "financial_ledger_entries" ADD CONSTRAINT "financial_ledger_entries_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "refund_allocations" ADD CONSTRAINT "refund_allocations_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "loyalty_accounts" ADD CONSTRAINT "loyalty_accounts_audit_amount_check" CHECK (balance >= 0) NOT VALID;
ALTER TABLE "loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_audit_amount_check" CHECK (balance_after >= 0) NOT VALID;
ALTER TABLE "loyalty_rules" ADD CONSTRAINT "loyalty_rules_audit_amount_check" CHECK (earn_points_per_amount >= 0 AND earn_amount_unit > 0 AND redemption_value_per_point > 0) NOT VALID;
ALTER TABLE "promotion_redemptions" ADD CONSTRAINT "promotion_redemptions_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "voucher_redemptions" ADD CONSTRAINT "voucher_redemptions_audit_amount_check" CHECK (amount >= 0) NOT VALID;
ALTER TABLE "pricing_snapshots" ADD CONSTRAINT "pricing_snapshots_audit_amount_check" CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND final_amount >= 0) NOT VALID;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_audit_amount_check" CHECK (total_amount >= 0 AND (voucher_discount_amount IS NULL OR voucher_discount_amount >= 0) AND (final_amount IS NULL OR final_amount >= 0)) NOT VALID;
ALTER TABLE "booking_services" ADD CONSTRAINT "booking_services_audit_amount_check" CHECK (price_at_booking >= 0 AND duration_minutes > 0) NOT VALID;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_audit_amount_check" CHECK (subtotal_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0 AND tax_rate >= 0 AND tax_rate <= 100) NOT VALID;
ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_audit_amount_check" CHECK (quantity > 0 AND unit_price >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND line_total >= 0 AND tax_rate >= 0 AND tax_rate <= 100) NOT VALID;
ALTER TABLE "branch_state_transitions" VALIDATE CONSTRAINT "branch_state_transitions_branch_id_fkey";
ALTER TABLE "branch_state_transitions" VALIDATE CONSTRAINT "branch_state_transitions_actor_id_fkey";
ALTER TABLE "price_adjustments" VALIDATE CONSTRAINT "price_adjustments_booking_id_fkey";
ALTER TABLE "price_adjustments" VALIDATE CONSTRAINT "price_adjustments_branch_id_fkey";
ALTER TABLE "price_adjustments" VALIDATE CONSTRAINT "price_adjustments_customer_id_fkey";
ALTER TABLE "promotion_redemptions" VALIDATE CONSTRAINT "promotion_redemptions_promotion_id_fkey";
ALTER TABLE "promotion_redemptions" VALIDATE CONSTRAINT "promotion_redemptions_booking_id_fkey";
ALTER TABLE "promotion_redemptions" VALIDATE CONSTRAINT "promotion_redemptions_customer_id_fkey";
ALTER TABLE "promotion_redemptions" VALIDATE CONSTRAINT "promotion_redemptions_branch_id_fkey";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_voucher_id_fkey";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_customer_voucher_id_fkey";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_customer_id_fkey";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_booking_id_fkey";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_branch_id_fkey";
ALTER TABLE "service_variants" VALIDATE CONSTRAINT "service_variants_service_id_fkey";
ALTER TABLE "service_price_rules" VALIDATE CONSTRAINT "service_price_rules_service_id_fkey";
ALTER TABLE "service_price_rules" VALIDATE CONSTRAINT "service_price_rules_variant_id_fkey";
ALTER TABLE "service_dependencies" VALIDATE CONSTRAINT "service_dependencies_service_id_fkey";
ALTER TABLE "service_dependencies" VALIDATE CONSTRAINT "service_dependencies_required_service_id_fkey";
ALTER TABLE "booking_service_adjustments" VALIDATE CONSTRAINT "booking_service_adjustments_booking_service_id_fkey";
ALTER TABLE "booking_service_adjustments" VALIDATE CONSTRAINT "booking_service_adjustments_booking_id_fkey";
ALTER TABLE "booking_service_adjustments" VALIDATE CONSTRAINT "booking_service_adjustments_actor_id_fkey";
ALTER TABLE "operational_impact_cases" VALIDATE CONSTRAINT "operational_impact_cases_business_id_fkey";
ALTER TABLE "operational_impact_cases" VALIDATE CONSTRAINT "operational_impact_cases_branch_id_fkey";
ALTER TABLE "operational_impact_cases" VALIDATE CONSTRAINT "operational_impact_cases_owner_id_fkey";
ALTER TABLE "operational_impact_cases" VALIDATE CONSTRAINT "operational_impact_cases_created_by_fkey";
ALTER TABLE "operational_impact_items" VALIDATE CONSTRAINT "operational_impact_items_case_id_fkey";
ALTER TABLE "operational_impact_items" VALIDATE CONSTRAINT "operational_impact_items_booking_id_fkey";
ALTER TABLE "operational_impact_items" VALIDATE CONSTRAINT "operational_impact_items_replacement_staff_id_fkey";
ALTER TABLE "operational_impact_items" VALIDATE CONSTRAINT "operational_impact_items_replacement_branch_id_fkey";
ALTER TABLE "operational_impact_items" VALIDATE CONSTRAINT "operational_impact_items_resolved_by_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_customer_id_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_business_id_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_branch_id_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_service_id_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_staff_id_fkey";
ALTER TABLE "waitlist_entries" VALIDATE CONSTRAINT "waitlist_entries_booking_id_fkey";
ALTER TABLE "review_moderation_events" VALIDATE CONSTRAINT "review_moderation_events_review_id_fkey";
ALTER TABLE "review_moderation_events" VALIDATE CONSTRAINT "review_moderation_events_actor_id_fkey";
ALTER TABLE "review_appeals" VALIDATE CONSTRAINT "review_appeals_review_id_fkey";
ALTER TABLE "review_appeals" VALIDATE CONSTRAINT "review_appeals_appellant_id_fkey";
ALTER TABLE "review_appeals" VALIDATE CONSTRAINT "review_appeals_reviewed_by_fkey";
ALTER TABLE "loyalty_rules" VALIDATE CONSTRAINT "loyalty_rules_business_id_fkey";
ALTER TABLE "loyalty_rules" VALIDATE CONSTRAINT "loyalty_rules_branch_id_fkey";
ALTER TABLE "loyalty_rules" VALIDATE CONSTRAINT "loyalty_rules_created_by_fkey";
ALTER TABLE "loyalty_accounts" VALIDATE CONSTRAINT "loyalty_accounts_business_id_fkey";
ALTER TABLE "loyalty_accounts" VALIDATE CONSTRAINT "loyalty_accounts_customer_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_account_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_business_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_customer_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_booking_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_refund_request_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_reversal_of_id_fkey";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_created_by_fkey";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_business_id_fkey";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_branch_id_fkey";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_booking_id_fkey";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_payment_id_fkey";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_created_by_fkey";
ALTER TABLE "invoice_lines" VALIDATE CONSTRAINT "invoice_lines_invoice_id_fkey";
ALTER TABLE "invoice_lines" VALIDATE CONSTRAINT "invoice_lines_booking_service_id_fkey";
ALTER TABLE "invoice_events" VALIDATE CONSTRAINT "invoice_events_invoice_id_fkey";
ALTER TABLE "invoice_events" VALIDATE CONSTRAINT "invoice_events_actor_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_business_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_old_owner_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_new_owner_user_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_legal_entity_version_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_payout_account_version_id_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_requested_by_fkey";
ALTER TABLE "ownership_transfers" VALIDATE CONSTRAINT "ownership_transfers_approved_by_fkey";
ALTER TABLE "ownership_history" VALIDATE CONSTRAINT "ownership_history_business_id_fkey";
ALTER TABLE "ownership_history" VALIDATE CONSTRAINT "ownership_history_owner_id_fkey";
ALTER TABLE "ownership_history" VALIDATE CONSTRAINT "ownership_history_transfer_id_fkey";
ALTER TABLE "legal_entity_versions" VALIDATE CONSTRAINT "legal_entity_versions_business_id_fkey";
ALTER TABLE "legal_entity_versions" VALIDATE CONSTRAINT "legal_entity_versions_created_by_fkey";
ALTER TABLE "payout_account_versions" VALIDATE CONSTRAINT "payout_account_versions_business_id_fkey";
ALTER TABLE "payout_account_versions" VALIDATE CONSTRAINT "payout_account_versions_created_by_fkey";
ALTER TABLE "customer_business_segments" VALIDATE CONSTRAINT "customer_business_segments_business_id_fkey";
ALTER TABLE "customer_business_segments" VALIDATE CONSTRAINT "customer_business_segments_customer_id_fkey";
ALTER TABLE "customer_business_segments" VALIDATE CONSTRAINT "customer_business_segments_assigned_by_fkey";
ALTER TABLE "customer_profiles" VALIDATE CONSTRAINT "customer_profiles_user_id_fkey";
ALTER TABLE "business_owner_profiles" VALIDATE CONSTRAINT "business_owner_profiles_user_id_fkey";
ALTER TABLE "payments" VALIDATE CONSTRAINT "payments_audit_amount_check";
ALTER TABLE "refund_requests" VALIDATE CONSTRAINT "refund_requests_audit_amount_check";
ALTER TABLE "payment_transactions" VALIDATE CONSTRAINT "payment_transactions_audit_amount_check";
ALTER TABLE "financial_ledger_entries" VALIDATE CONSTRAINT "financial_ledger_entries_audit_amount_check";
ALTER TABLE "refund_allocations" VALIDATE CONSTRAINT "refund_allocations_audit_amount_check";
ALTER TABLE "loyalty_accounts" VALIDATE CONSTRAINT "loyalty_accounts_audit_amount_check";
ALTER TABLE "loyalty_transactions" VALIDATE CONSTRAINT "loyalty_transactions_audit_amount_check";
ALTER TABLE "loyalty_rules" VALIDATE CONSTRAINT "loyalty_rules_audit_amount_check";
ALTER TABLE "promotion_redemptions" VALIDATE CONSTRAINT "promotion_redemptions_audit_amount_check";
ALTER TABLE "voucher_redemptions" VALIDATE CONSTRAINT "voucher_redemptions_audit_amount_check";
ALTER TABLE "pricing_snapshots" VALIDATE CONSTRAINT "pricing_snapshots_audit_amount_check";
ALTER TABLE "bookings" VALIDATE CONSTRAINT "bookings_audit_amount_check";
ALTER TABLE "booking_services" VALIDATE CONSTRAINT "booking_services_audit_amount_check";
ALTER TABLE "invoices" VALIDATE CONSTRAINT "invoices_audit_amount_check";
ALTER TABLE "invoice_lines" VALIDATE CONSTRAINT "invoice_lines_audit_amount_check";
CREATE INDEX "bookings_branch_id_appointment_date_status_idx" ON "bookings"("branch_id", "appointment_date", "status");
CREATE INDEX "notifications_user_id_is_read_idx" ON "notifications"("user_id", "is_read");
CREATE INDEX "payments_created_at_idx" ON "payments"("created_at");
COMMIT;
